config/routes.rb
OpenCongress::Application.routes.draw do
  # API
  constraints :subdomain => 'api' do
    match '/' => redirect(Settings.base_url + 'api')
    match '/bill/text_summary/:id' => 'bill#status_text'
    match '/roll_call/text_summary/:id' => 'roll_call#summary_text'
    with_options :format => [:json, :xml] do |f|
      f.match '/groups(.:format)' => 'groups#index'
      f.match '/groups(/:id(.:format))' => 'groups#show'
    end
    match '/:action(/:id)', :controller => 'api'
  end

  resources :mailing_list_items
  resources :watch_dogs

  resources :states do
    resources :districts
  end

  resources :groups do
    resources :group_invites
    resources :group_members
    resources :group_bill_positions
    
    resource :political_notebook do
      resources :notebook_items do
        collection do
          get :feed
        end
      end
      resources :notebook_links
      resources :notebook_videos
      resources :notebook_notes
      resources :notebook_files    
    end
  end
  
  resources :simple_captcha, :only => :show
  
  match '/' => 'index#index', :as => :home

  # Allow downloading Web Service WSDL as a file with an extension
  # instead of a file named 'wsdl'
  # match ':controller/service.wsdl' => 'wsdl'

  # Handle bill routing. The action determines what information about the bill will 
  # be displayed.
  match 'bill/:id/users_tracking' => 'friends#tracking_bill', :as => :users_tracking_bill
  match 'bill/:id/users_tracking/:state' => 'friends#tracking_bill', :state => /\w{2}/, :as => :users_tracking_bill_by_state

  scope 'bill', :controller => 'bill' do
    for action in %w{ all pending popular major hot readthebill compare compare_by_issues atom_top20 }
      match action, :action => action, :as => 'bill_' + action
    end

    match 'most/:type', :action => 'most_commentary', :as => :bill_most_commentary
    match 'most/viewed', :action => 'popular'
    match 'atom/most/viewed', :action => 'atom_top20'
    match 'atom/most/:type', :action => 'atom_top_commentary'
    match 'type/:bill_type(/:page)', :action => 'list_bill_type'
    match 'text/status/:id', :action => 'status_text'
    match 'upcoming/:id', :action => 'upcoming'
    match 'bill_vote/:bill/:id', :action => 'bill_vote'

    scope ':id' do
      match 'blogs(/:page)', :action => 'blogs', :as => :blogs_bill
      match 'blogs/search(/:page)', :action => 'commentary_search', :commentary_type => 'blog'        
      match 'news(/:page)', :action => 'news', :as => :news_bill
      match 'news/search(/:page)', :action => 'commentary_search', :commentary_type => 'news'        
      match 'text', :action => 'text', :as => :bill_text
      match 'comments', :action => 'comments', :as => :bill_comments
      match 'show', :action => 'show', :as => :bill
      match ':action'
    end

    match ':id' => 'bill#show'

  end
  match 'bill' => redirect('/bill/all')

  scope 'people', :controller => 'people' do
    match 'senators', :action => 'people_list', :person_type => 'senators'
    match 'representatives', :action => 'people_list', :person_type => 'representatives'
    match ':person_type/most/:type', :action => 'most_commentary'
    match ':person_type/atom/most/:type', :action => 'atom_top_commentary'
    match 'atom/featured', :action => 'atom_featured'
    match 'wiki/:id', :action => 'wiki'
    match 'comments/:id', :action => 'comments'
    match 'news/:id(/:page)', :action => 'news', :as => :news_person
    match 'blogs/:id(/:page)', :action => 'blogs', :as => :blogs_person
    match 'votes_with_party/:chamber/:party', :action => 'votes_with_party'
    match 'voting_history/:id/:page', :action => 'voting_history'
    match 'compare.:format', :action => 'compare'
    match 'show/:id', :action => 'show', :as => 'person'
  end

  match 'person/*path' => redirect("/people/%{path}")

  namespace :admin do
     resources :wiki_links, :pvs_category_mappings, :talking_points
     resources :articles do
       collection do
         get :list
         get :edit_blogroll
       end
       resources :article_images
     end

     match '/' => 'index#index', :as => 'admin'
     
     scope 'stats', :controller => 'stats' do
       match 'bills.:format', :action => 'bills'
       match 'partner_email.:format', :action => 'partner_email'
     end
     
     match 'contact_congress' => 'contact_congress#index'
     match 'contact_congress/letters' => 'contact_congress#letters'
  end
  match '/:controller(/:action(/:id))', :controller => /admin\/[^\/]+/
  

  match 'battle_royale' => 'battle_royale#index'
  match 'battle_royale/:action', :controller => 'battle_royale'

  match 'blog(/:tag)' => 'articles#list', :as => :blogs
  
  scope 'articles', :controller => 'articles' do
    match 'view/:id', :action => 'view', :as => :article
    match ':id/atom', :action => 'article_atom'
  end

  match 'issues' => 'issue#index'

  scope 'issues', :controller => 'issue' do
    match 'show/:id', :action => 'show', :as => :issue
    match ':action/:id'
  end

  
  #######TEMP REMOVE
  # scope :module => 'formageddon', :as => 'formageddon' do    
  #   resources :formageddon_threads, :controller => 'threads', :path => '/formageddon/threads'
  #   resources :formageddon_contact_steps, :controller => 'contact_steps', :path => '/formageddon/contact_steps'
  # end
  # 
  # 
  # 
  # 
  # 
  # # Install the default route as the lowest priority.
  # map.connect ':controller/:action/:id'
  

  resources :contact_congress_letters, :only => [:index, :show, :new, :update] do
    get 'create_from_formageddon', :on => :collection # create uses POST and we'll be redirecting to create
    get 'get_recipients', :on => :collection 
    get 'delayed_send', :on => :collection
    get 'get_replies', :on => :collection
  end
  
  match 'howtouse' => 'about#howtouse'
  
  scope :controller => 'account' do
    for action in %w{ login why logout signup welcome contact_congress}
      match action, :action => action
    end
    
    match 'register', :action => 'signup'
    match 'account/confirm/:login', :action => 'confirm'
  end

  scope :controller => 'comments' do
    match 'comments/all_comments/:object/:id', :action => 'all_comments'
    match 'comments/atom/:object/:id', :action => 'atom_comments'
  end

  match 'users/:login/profile' => 'profile#show', :as => :user_profile

  scope 'users/:login' do

    scope 'profile' do 
      resource :political_notebook do
        collection do
          post :update_privacy
          get :feed
        end
        resources :notebook_links do
          collection do
            get :faceform
          end
        end
        resources :notebook_videos
        resources :notebook_notes
        resources :notebook_files    
      end
    
      scope 'friends', :controller => 'friends' do
        for action in %w{ import_contacts like_voters invite_contacts near_me invite invite_form }
          match action, :action => action, :as => 'friends_' + action
        end

        for action in %w{ confirm deny } do
          match action + '/:id', :action => action, :as => 'friends_add_' + action
        end
      end
  
      resources :friends

      scope :controller => 'profile' do
        for action in %w{ actions items_tracked watchdog edit_profile bills_supported tracked_rss user_actions_rss bills_opposed my_votes bills comments issues committees groups } do
          match action, :action => action, :as => 'user_' + action
        end

        match ':person_type', :action => 'person'
      end
    end # profile
    
    match 'feeds/:action(/:key)', :controller => 'user_feeds'
    
  end # users/:login

  match 'video/rss' => 'video#all', :format => 'atom'

  scope :controller => 'roll_call' do
    match 'roll_call/text/summary/:id', :action => 'summary_text'      
    match 'vote/:year/:chamber/:number(/:state)', :action => 'by_number', :year => /\d{4}/, :chamber => /[hs]/, :number => /\d+/, :state => /\w{2}/
  end

  match 'tools(/:action(/:id))', :controller => 'resources', :as => 'tools'

  match '/widgets' => 'widgets#index', :as => 'widgets'
  match '/widgets/deprecated' => 'widgets#deprecated', :as => 'deprecated_widgets'
  match '/widgets/bill' => 'widgets#bill', :as => 'bill_widget'
  match '/widgets/bills' => 'widgets#bills', :as => 'bills_widget'
  match '/widgets/people' => 'widgets#people', :as => 'people_widget'
  match '/widgets/group' => 'widgets#group', :as => 'group_widget'

  match 'api' => 'api#index'
  match 'api/bill/text_summary/:id' => 'bill#status_text'
  match 'api/roll_call/text_summary/:id' => 'roll_call#summary_text'
  match 'api(/:action(/:id)(.:format))', :controller => 'api'

  # Temporary routes for health care legislation
  match 'baucus_bill_health_care.html' => 'index#s1796_redirect'
  match 'presidents_health_care_proposal' => 'index#presidents_health_care_proposal'
  match 'senate_health_care_bill' => 'bill#text', :id => '111-h3590', :version => 'ocas'
  match 'house_reconciliation' => 'index#house_reconciliation'
  match 'pipa' => 'index#pipa'

  match ':controller(/:action(/:id))'
  #match '*path' => 'index#notfound' #unless Rails.application.config.consider_all_requests_local
  
end  

app/models/political_notebook.rb
class PoliticalNotebook < ActiveRecord::Base
  belongs_to :user  
  belongs_to :group
  
  has_many :notebook_items, :order => 'created_at DESC', :dependent => :destroy #sti, all

  has_many :notebook_links
  has_many :notebook_videos    
  has_many :notebook_notes    
  has_many :notebook_files
  
  def atom_id
    "tag:opencongress.org,#{created_at.strftime("%Y-%m-%d")}:/political_notebook/#{id}"
  end
  
  def self.find_or_create_from_user(user)
    if user.political_notebook.blank?
      pn = PoliticalNotebook.new
      pn.user_id = user.id
      pn.save
      pn
    else
      user.political_notebook
    end
  end
  
  def self.find_or_create_from_group(group)
    if group.political_notebook.blank?
      pn = PoliticalNotebook.new
      pn.group_id = group.id
      pn.save
      group.save
      
      pn
    else
      group.political_notebook
    end
  end

  def already_contains?(object)
    self.notebook_links.count(:conditions =>["notebook_items.notebookable_id = ? and notebook_items.notebookable_type = ?", object.id, object.class.to_s]) > 0
  end  
  
  def can_view?(viewer)
    if self.group.nil?
      return self.user.can_view('my_political_notebook',viewer)    
    else
      return ((self.group.join_type != 'INVITE_ONLY') && self.group.is_member?(viewer))
    end
  end
  
  def can_edit?(editor)
    return false if (editor == :false)
    if self.group.nil?
      return PoliticalNotebook.find_or_create_from_user(editor) === self
    else
      return self.group.can_post?(editor)
    end
  end
end

app/controllers/political_notebooks_controller.rb
class PoliticalNotebooksController < ApplicationController
  require 'hpricot'
  require 'open-uri'
  require 'timeout'
  
  helper :profile
  before_filter :login_required, :only => :bookmarklet_add
  before_filter :get_user, :set_title, :set_profile_nav_location, :except => :bookmarklet_add
  before_filter :get_notebook, :except => ['update_privacy','bookmarklet_add']

  def show
    @atom = {'link' => url_for(:only_path => false, :controller => 'notebook_items', :action => 'feed'), 'title' => "#{@user.login}'s My Political Notebook Feed"}
    @hide_atom = true
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @political_notebook }
    end
  end

  def update_privacy
    @user = current_user
    params[:privacy_option].delete("user_id")
    @user.privacy_option.update_attributes(params[:privacy_option])
    redirect_to political_notebook_path({:login =>current_user.login})
  end

  def bookmarklet_add    
    @user = current_user
    @political_notebook = current_user.political_notebook
    @can_view = @can_edit = true
    @items = @political_notebook.notebook_items.paginate(:page => 1, :per_page => 5)
    @from_bookmarklet = true
    
    @page_title = "My Political Notebook"
    @title_class = "tab-nav notebook"    
    @profile_nav = @user
    stc = ScrapeToolsController.new

    # check for youtube for now
    if params[:url] =~ /^http:\/\/www.youtube.com\//

      @notebook_video = NotebookLink.new
      @notebook_video.url = params[:url]
      @notebook_video.embed = get_youtube_embed(params[:url])
      @notebook_video.title = get_url_title(params[:url])
      
    else
      @notebook_link = NotebookLink.new
      @notebook_link.url = params[:url]
      @notebook_link.title = get_url_title(params[:url])
    end
    
    render :action => 'show'
  end
  
private
  def set_title
    if @user == current_user
      @page_title = "My Political Notebook"
    else
      @page_title = "#{@user.login}'s Political Notebook"    
    end
  end

  def set_profile_nav_location
  	@title_class = "tab-nav notebook"    
    @profile_nav = @user    
  end

  def get_user
    @user = User.find_by_login(params[:login])
  end

  def get_notebook
    @political_notebook = PoliticalNotebook.find_or_create_from_user(@user)
    @page = params[:page] ||= 1
    @tag = params[:tag] ||= nil   
    @type = params[:type] ||= nil
    if @tag && @type
      @items = @political_notebook.notebook_items.tagged_with(@tag, :conditions => ["type = ?", @type])
    elsif @tag
      @items = @political_notebook.notebook_items.tagged_with @tag
    elsif @type
      @items = @political_notebook.notebook_items.find(:all, :conditions => ["type = ?", @type])
    else
      @items = @political_notebook.notebook_items
    end
    @items = @items.paginate(:page => @page, :per_page => 5)
    @can_edit = is_users_notebook?
    @can_view = @political_notebook.can_view?(current_user)
  end
  
  def is_users_notebook?
    return false unless logged_in?
    return current_user == @political_notebook.user
  end
  
  def get_url_title(url)
    title = ""
    unless url.blank?
      regex = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/    
      if url =~ regex
        begin
          Timeout::timeout(3) {
            doc = Hpricot(open(url))
            title = (doc/"title").inner_html
          }
        rescue Timeout::Error
          title = ""
        end
      end
    end
    title
  end

  def get_youtube_embed(url)
    embed = ""
    unless url.blank?
      regex = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/    
      if url =~ regex
        doc = Hpricot(open(url))
        doc.at("input#embed_code")['value']
        embed = CGI::unescapeHTML(doc.at("input#embed_code")['value'])
      end
    end
    embed
  end 
end

app/helpers/political_notebooks_helper.rb
module PoliticalNotebooksHelper
  
  def get_label
    @label = ""
    if @type
      case @type
        when 'NotebookFile'
          @label += 'Files '
        when 'NotebookNote'
          @label += 'Notes '
        when 'NotebookLink'
          @label += 'Links '
        when 'NotebookVideo'
          @label += 'Videos '
      end
    else @label += 'All Items '
    end
    if @tag
      @label += "Tagged With '#{@tag}'"
    end
    return @label
  end
      
  def image_for(file, size = '') 
    image_tag("#{Settings.base_url}#{file.public_filename(size)}")
  end
  
  def div_height(y)
    ymod = y % 24
    div_y = (24 - ymod) + y
    return div_y
  end

  def is_on(type)
    if @type == type
      "on"
    else
      "off"
    end
  end
    
end

app/views/political_notebooks/_item_meta.html.erb
<% item = item_meta %>
<span>Added <%= time_ago_in_words item.created_at %> ago -
	<% if item.count_times_bookmarked > 1 %>
	<script type='text/javascript'>
	$j().ready(function() {
		$j('#other-bookmarked-<%= item.id %>').jqm({trigger: '.meta-info-<%= item.id %>'});
	});
  </script>
	Added by <a href="#" class="meta-info-<%= item.id %>"><%= item.count_times_bookmarked - 1 %> other users</a>.
  	<div id="other-bookmarked-<%= item.id %>" class="notebook-form-div" style="display:none">
  	  <h3>Other Users that have bookmarked "<%= item.title %>"</h3>
  	  <% item.other_users_bookmarked.each do |u| %>
  	    <%= link_to h(u.login), user_profile_path(u.login) %><br />
  	  <% end %>
    </div>
	<% end %>
	<% if item.tags.any? %>
	Tagged with 
		<% item.tags.each do |tag| %>
			<%= link_to h(tag.name), political_notebook_path({:login => item.political_notebook.user.login, :tag=> tag.name, :type => item.type}) %>&nbsp;-
		<% end %>
	<% end %>
	<% if item.hot_bill_category %>
	  Issue area of <%= item.hot_bill_category.name %>
	  (<a href="/bill/hot#<%= item.hot_bill_category.name %>">View hot bills</a>)&nbsp;-
	<% end %>
	<% if( !item.notebookable.blank?) && (item.notebookable.is_a? Commentary )%>

		<% commentary = item.notebookable%>
	    <% if commentary.source_url %>
	      <% if commentary.source %>      
	        Source: <a href="<%= commentary.source_url %>" target="_blank"><%= strip_tags(commentary.source) %></a>
	      <% else %>
	        Source: <a href="<%= commentary.source_url %>" target="_blank"><%= commentary.source_url %></a></p>
	      <% end %>
	    <% else %>
	      <% if commentary.source %>
	        Source: <%= commentary.source %>
	      <% end %>
	    <% end %>
      &nbsp;-
	<% end %>
	<% if current_user == item.political_notebook.user %>
		<script type='text/javascript'>
		$j().ready(function() {
			$j('#edit-link-<%= item.id %>').jqm({trigger: '.meta-edit-<%= item.id %>'});
		});
		</script>
	  <span style="font-style: normal;">
	    <a href="#edit-link-<%= item.id %>" class="meta-edit-<%= item.id %>">Edit</a> / 
	    <%= link_to "Delete", { :controller => 'notebook_items', :action => 'remove_item', :id => item, :page => @page }, { :confirm => "Are you sure you want to delete this item?" } %></span>
	<% end %>
	<div id="edit-link-<%= item.id %>" class="notebook-form-div jqmWindow" style="display:none">
	  <% @notebook_item = item %>
  	<%= render :partial => "#{item.class.to_s.tableize}/inline_edit_form"  %>
  </div>
</span>

app/views/political_notebooks/edit.html.erb
<h1>Editing political_notebook</h1>

<%= error_messages_for :political_notebook %>

<% form_for(@political_notebook) do |f| %>
  <p>
    <b>User</b><br />
    <%= f.text_field :user_id %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @political_notebook %> |
<%= link_to 'Back', political_notebooks_path %>

app/views/political_notebooks/index.html.erb
<h1>Listing political_notebooks</h1>

<table>
  <tr>
    <th>User</th>
  </tr>

<% for political_notebook in @political_notebooks %>
  <tr>
    <td><%=h political_notebook.user_id %></td>
    <td><%= link_to 'Show', political_notebook %></td>
    <td><%= link_to 'Edit', edit_political_notebook_path(political_notebook) %></td>
    <td><%= link_to 'Destroy', political_notebook, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New political_notebook', new_political_notebook_path %>

app/views/political_notebooks/new.html.erb
<h1>New political_notebook</h1>

<%= error_messages_for :political_notebook %>

<% form_for(@political_notebook) do |f| %>
  <p>
    <b>User</b><br />
    <%= f.text_field :user_id %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', political_notebooks_path %>

app/views/political_notebooks/show.html.erb
<div id="heading">
  <h2><%= @user.login %>'s Political Notebook</h2>
</div>
<div class="padding">
  <% if @can_view %>
  <% if @can_edit %>
  <div id="bookmarklet">
  	<a href="javascript:w=window.open('<%= Settings.base_url %>political_notebooks/bookmarklet_add?url='+escape(location.href),'OCbookmarklet', 'width=1020,height=635,scrollbars=1');setTimeout('w.focus()',50);void(0);"><%= image_tag 'bookmark-trans.png', :alt => '+MyPN', :title => 'Bookmarklet' %></a>
  </div>
  <script type="text/javascript">
	$j().ready(function(){
		$j("#bookmarklet").qtip({
			content: "Drag this bookmarklet into your brower's toolbar (Internet Explorer users should right-click and select \"add to favorites\"), and it will instantly add pages from around the web to Your Political Notebook.",
			show: 'mouseover',
			hide: 'mouseout',
			position:{
				corner: {
					target: 'bottomLeft',
					tooltip: 'topRight'
				}
			},
			style: {
				border: {
					width: 2,
					radius: 5,
					color: '#BBBBBB'
				},
				tip: {
					corner: 'topRight',
					color: '#999999',
					size: {
						x:20,
						y:12
						}
					}
			}
		})
	});
	</script>  	


  <div id="privacy">
  	<% form_for :privacy_option, @user.privacy_option,:url => update_privacy_political_notebook_path({:login =>@user.login}) do |f| %>
  	<span class="notebookPrivacy"><%= image_tag("private.png", :alt => "private",:id => 'Privacy') %></span><%= f.select PrivacyOption.column_names[PrivacyOption.column_names.index 'my_political_notebook'].to_sym, [["Public",2],["Friends", 1], ["Private",0]], {}, {:onchange => "this.form.submit();"} %>
  	<% end %>
    <script type="text/javascript">
		$j().ready(function(){
			$j("#privacy").qtip({
				content: "Who can see My Political Notebook?",
				show: 'mouseover',
				hide: 'mouseout',
				position:{
					corner: {
						target: 'bottomLeft',
						tooltip: 'topRight'
					}
				},
				style: {
					border: {
						width: 2,
						radius: 5,
						color: '#BBBBBB'
					},
					tip: {
						corner: 'topRight',
						color: '#999999',
						size: {
							x:20,
							y:12
							}
						}
				}
			})
		});
		</script>  	
  </div>

  <%= render :partial => 'toolbar' %>	
  <% else %>
  <br style="clear:both;" />
  <% end %>
  <div style="margin-top:4px;" class="explain_box">
  	Save and share your favorite political content, from OpenCongress and around the web. <%= link_to "Learn how to get started.", {:controller => 'about', :action => 'political_notebooks'}, :class => 'arrow' %>
  </div>
  <div id="the-items">
  	<ul id="pn_tabs">
  		<li>
  			<%= link_to "All Items", political_notebook_path({:login => @user.login, :tag=> @tag, :type => nil}), :id => "all_tab", :class => is_on(nil) %>
  		</li>
  		<li>
  			<%= link_to "Links", political_notebook_path({:login => @user.login, :tag=> @tag, :type => "NotebookLink"}), :id => "links_tab", :class => is_on("NotebookLink") %>
  		</li>
  		<li>
  			<%= link_to "Videos", political_notebook_path({:login => @user.login, :tag=> @tag, :type => "NotebookVideo"}), :id => "videos_tab", :class => is_on("NotebookVideo") %>
  		</li>
  		<li>
  			<%= link_to "Notes", political_notebook_path({:login => @user.login, :tag=> @tag, :type => "NotebookNote"}), :id => "notes_tab", :class => is_on("NotebookNote") %>
  		</li>
  		<li>
  			<%= link_to "Files", political_notebook_path({:login => @user.login, :tag=> @tag, :type => "NotebookFile"}), :id => "files_tab", :class => is_on("NotebookFile") %>
  		</li>
  	</ul>

  	<% if @from_bookmarklet %>
  	<div id="add-link-bookmarklet">
  		<div id="facebox" style="top:140px;"> 
  			<div class="popup"> 
  				<table> 
  					<tbody> 
  						<tr> 
  							<td class="tl"/><td class="b"/><td class="tr"/> 
  						</tr> 
  						<tr> 
  							<td class="b"/> 
  							<td class="body"> 
  								<div class="content">
  									<% if @notebook_link %>  
  									<%= render :partial => "notebook_links/inline_form", :locals => { :from_bookmarklet => 'true' } %>                    
  									<% elsif @notebook_video %>
  									<%= render :partial => "notebook_videos/inline_form", :locals => { :from_bookmarklet => 'true' } %>
  									<% end %>
  								</div> 
  								<div class="footer"> 
  									<a href="#" class="close"> 
  										<%= image_tag 'facebox/closelabel.gif', :title => 'close', :class => 'close_image' %> 
  									</a> 
  								</div> 
  							</td> 
  							<td class="b"/> 
  						</tr> 
  						<tr> 
  							<td class="bl"/><td class="b"/><td class="br"/> 
  						</tr> 
  					</tbody> 
  				</table> 
  			</div> 
  		</div>
  	</div>
  	<% end %>

  	<div class="notebook_bottom">
      <%= will_paginate @items, :params => {:controller => 'notebook_items', :action => '', :login => @user.login } %>		
      
  		<div class="notebook_top">                      
			
  			<h3 class="dark inline"> <%= get_label %><%= link_to "[remove tag filter]", political_notebook_path({:login => @user.login, :tag=> nil, :type => @type}), :id => "no_tags" if @tag %></h3>
  			<div class="notebook_content">
  				<% if @can_edit %>
  					<% unless @from_bookmarklet %>
  						<div id="no-items" style="display:<%= (@political_notebook.notebook_items.any?) ? 'none' : '' %>">
  						You haven't added any items to your Political Notebook.  Use the links above to get started.
  					</div>
  					<% end %>
  				<% end %>

  				<ul id="notebook-items" class="notebook_items">
  					<% @items.each do |item| %>
  					<li><%= render :partial => "#{item.class.to_s.tableize}/listitem", :object => item %></li>
  					<% end %>		
  				</ul>            
  			</div>
  		</div>
  	</div>
  </div>   
  <div class="hints">
  <% case @type
  when "NotebookLink" %>
  <p>Here you can add links to any webpage from OpenCongress or around the web. For example, on an OpenCongress <a href="/bill/110-h1424/show">bill page</a>, click on the "+" next to the official bill number to add it here. Or, if you're reading a news article or blog post elsewhere on the web, use the bookmarklet to save it back here with your notes and remember it later. Don't forget the <a href="/blog">OpenCongress Blog</a> &mdash; for example, <a href="/articles/view/721-Obama-and-McCain-Legislative-Accomplishments">a post</a> comparing Sen. McCain and Sen. Obama's legislative accomplishments. Finally, you can bookmark any comment you value from users on OpenCongress &mdash; for example, <a href="/bill/110-h5749/show?goto_comment=20220">a call to action</a> on an Unemployment Bill. </p>
  	<% when "NotebookVideo" %>
  <p>
  	Here you can embed any streaming video from around the web. For example, if you're watching <a href="http://www.youtube.com/watch?v=Mn5VathNJH4">a video</a> you want to save and share, copy-and-paste all the code to "Embed", and you'll be able to watch it here.
  </p>
  	<% when "NotebookNote" %>         
  <p>Here you can add notes or thoughts you feel might be interesting to other users. Or simply as a reminder to yourself.</p>  
  	<% when "NotebookFile" %>                   
  	<p>Here you can upload files to save and share. For example, you might upload a <a href="http://2.bp.blogspot.com/_ov-pT1x-W8Y/SPZoiO-1fOI/AAAAAAAADAA/iBez5Ho3Svs/S1600-R/1013_super.png">polling graph</a>, or a <a href="http://www.publicknowledge.org/pdf/youtube-letter-20080514.pdf">.pdf</a> of a press release or a proposed bill. </p>
  	<% else %>
  	<p>To see different types of content to add to "My Political Notebook", click on any of the tabs on the right-hand side of this page. To see an example of a fleshed-out notebook, visit the page of <a href="/users/donnyshaw/profile/political_notebook">Donny Shaw</a>, our blog and outreach director.</p>
  	<% end %>
  </div>
  <% else %>
  	You currently don't have access to view this user's Political Notebook
  <% end %>
</div>