config/routes.rb
OpenCongress::Application.routes.draw do
  # API
  constraints :subdomain => 'api' do
    match '/' => redirect(Settings.base_url + 'api')
    match '/bill/text_summary/:id' => 'bill#status_text'
    match '/roll_call/text_summary/:id' => 'roll_call#summary_text'
    with_options :format => [:json, :xml] do |f|
      f.match '/groups(.:format)' => 'groups#index'
      f.match '/groups(/:id(.:format))' => 'groups#show'
    end
    match '/:action(/:id)', :controller => 'api'
  end

  resources :mailing_list_items
  resources :watch_dogs

  resources :states do
    resources :districts
  end

  resources :groups do
    resources :group_invites
    resources :group_members
    resources :group_bill_positions
    
    resource :political_notebook do
      resources :notebook_items do
        collection do
          get :feed
        end
      end
      resources :notebook_links
      resources :notebook_videos
      resources :notebook_notes
      resources :notebook_files    
    end
  end
  
  resources :simple_captcha, :only => :show
  
  match '/' => 'index#index', :as => :home

  # Allow downloading Web Service WSDL as a file with an extension
  # instead of a file named 'wsdl'
  # match ':controller/service.wsdl' => 'wsdl'

  # Handle bill routing. The action determines what information about the bill will 
  # be displayed.
  match 'bill/:id/users_tracking' => 'friends#tracking_bill', :as => :users_tracking_bill
  match 'bill/:id/users_tracking/:state' => 'friends#tracking_bill', :state => /\w{2}/, :as => :users_tracking_bill_by_state

  scope 'bill', :controller => 'bill' do
    for action in %w{ all pending popular major hot readthebill compare compare_by_issues atom_top20 }
      match action, :action => action, :as => 'bill_' + action
    end

    match 'most/:type', :action => 'most_commentary', :as => :bill_most_commentary
    match 'most/viewed', :action => 'popular'
    match 'atom/most/viewed', :action => 'atom_top20'
    match 'atom/most/:type', :action => 'atom_top_commentary'
    match 'type/:bill_type(/:page)', :action => 'list_bill_type'
    match 'text/status/:id', :action => 'status_text'
    match 'upcoming/:id', :action => 'upcoming'
    match 'bill_vote/:bill/:id', :action => 'bill_vote'

    scope ':id' do
      match 'blogs(/:page)', :action => 'blogs', :as => :blogs_bill
      match 'blogs/search(/:page)', :action => 'commentary_search', :commentary_type => 'blog'        
      match 'news(/:page)', :action => 'news', :as => :news_bill
      match 'news/search(/:page)', :action => 'commentary_search', :commentary_type => 'news'        
      match 'text', :action => 'text', :as => :bill_text
      match 'comments', :action => 'comments', :as => :bill_comments
      match 'show', :action => 'show', :as => :bill
      match ':action'
    end

    match ':id' => 'bill#show'

  end
  match 'bill' => redirect('/bill/all')

  scope 'people', :controller => 'people' do
    match 'senators', :action => 'people_list', :person_type => 'senators'
    match 'representatives', :action => 'people_list', :person_type => 'representatives'
    match ':person_type/most/:type', :action => 'most_commentary'
    match ':person_type/atom/most/:type', :action => 'atom_top_commentary'
    match 'atom/featured', :action => 'atom_featured'
    match 'wiki/:id', :action => 'wiki'
    match 'comments/:id', :action => 'comments'
    match 'news/:id(/:page)', :action => 'news', :as => :news_person
    match 'blogs/:id(/:page)', :action => 'blogs', :as => :blogs_person
    match 'votes_with_party/:chamber/:party', :action => 'votes_with_party'
    match 'voting_history/:id/:page', :action => 'voting_history'
    match 'compare.:format', :action => 'compare'
    match 'show/:id', :action => 'show', :as => 'person'
  end

  match 'person/*path' => redirect("/people/%{path}")

  namespace :admin do
     resources :wiki_links, :pvs_category_mappings, :talking_points
     resources :articles do
       collection do
         get :list
         get :edit_blogroll
       end
       resources :article_images
     end

     match '/' => 'index#index', :as => 'admin'
     
     scope 'stats', :controller => 'stats' do
       match 'bills.:format', :action => 'bills'
       match 'partner_email.:format', :action => 'partner_email'
     end
     
     match 'contact_congress' => 'contact_congress#index'
     match 'contact_congress/letters' => 'contact_congress#letters'
  end
  match '/:controller(/:action(/:id))', :controller => /admin\/[^\/]+/
  

  match 'battle_royale' => 'battle_royale#index'
  match 'battle_royale/:action', :controller => 'battle_royale'

  match 'blog(/:tag)' => 'articles#list', :as => :blogs
  
  scope 'articles', :controller => 'articles' do
    match 'view/:id', :action => 'view', :as => :article
    match ':id/atom', :action => 'article_atom'
  end

  match 'issues' => 'issue#index'

  scope 'issues', :controller => 'issue' do
    match 'show/:id', :action => 'show', :as => :issue
    match ':action/:id'
  end

  
  #######TEMP REMOVE
  # scope :module => 'formageddon', :as => 'formageddon' do    
  #   resources :formageddon_threads, :controller => 'threads', :path => '/formageddon/threads'
  #   resources :formageddon_contact_steps, :controller => 'contact_steps', :path => '/formageddon/contact_steps'
  # end
  # 
  # 
  # 
  # 
  # 
  # # Install the default route as the lowest priority.
  # map.connect ':controller/:action/:id'
  

  resources :contact_congress_letters, :only => [:index, :show, :new, :update] do
    get 'create_from_formageddon', :on => :collection # create uses POST and we'll be redirecting to create
    get 'get_recipients', :on => :collection 
    get 'delayed_send', :on => :collection
    get 'get_replies', :on => :collection
  end
  
  match 'howtouse' => 'about#howtouse'
  
  scope :controller => 'account' do
    for action in %w{ login why logout signup welcome contact_congress}
      match action, :action => action
    end
    
    match 'register', :action => 'signup'
    match 'account/confirm/:login', :action => 'confirm'
  end

  scope :controller => 'comments' do
    match 'comments/all_comments/:object/:id', :action => 'all_comments'
    match 'comments/atom/:object/:id', :action => 'atom_comments'
  end

  match 'users/:login/profile' => 'profile#show', :as => :user_profile

  scope 'users/:login' do

    scope 'profile' do 
      resource :political_notebook do
        collection do
          post :update_privacy
          get :feed
        end
        resources :notebook_links do
          collection do
            get :faceform
          end
        end
        resources :notebook_videos
        resources :notebook_notes
        resources :notebook_files    
      end
    
      scope 'friends', :controller => 'friends' do
        for action in %w{ import_contacts like_voters invite_contacts near_me invite invite_form }
          match action, :action => action, :as => 'friends_' + action
        end

        for action in %w{ confirm deny } do
          match action + '/:id', :action => action, :as => 'friends_add_' + action
        end
      end
  
      resources :friends

      scope :controller => 'profile' do
        for action in %w{ actions items_tracked watchdog edit_profile bills_supported tracked_rss user_actions_rss bills_opposed my_votes bills comments issues committees groups } do
          match action, :action => action, :as => 'user_' + action
        end

        match ':person_type', :action => 'person'
      end
    end # profile
    
    match 'feeds/:action(/:key)', :controller => 'user_feeds'
    
  end # users/:login

  match 'video/rss' => 'video#all', :format => 'atom'

  scope :controller => 'roll_call' do
    match 'roll_call/text/summary/:id', :action => 'summary_text'      
    match 'vote/:year/:chamber/:number(/:state)', :action => 'by_number', :year => /\d{4}/, :chamber => /[hs]/, :number => /\d+/, :state => /\w{2}/
  end

  match 'tools(/:action(/:id))', :controller => 'resources', :as => 'tools'

  match '/widgets' => 'widgets#index', :as => 'widgets'
  match '/widgets/deprecated' => 'widgets#deprecated', :as => 'deprecated_widgets'
  match '/widgets/bill' => 'widgets#bill', :as => 'bill_widget'
  match '/widgets/bills' => 'widgets#bills', :as => 'bills_widget'
  match '/widgets/people' => 'widgets#people', :as => 'people_widget'
  match '/widgets/group' => 'widgets#group', :as => 'group_widget'

  match 'api' => 'api#index'
  match 'api/bill/text_summary/:id' => 'bill#status_text'
  match 'api/roll_call/text_summary/:id' => 'roll_call#summary_text'
  match 'api(/:action(/:id)(.:format))', :controller => 'api'

  # Temporary routes for health care legislation
  match 'baucus_bill_health_care.html' => 'index#s1796_redirect'
  match 'presidents_health_care_proposal' => 'index#presidents_health_care_proposal'
  match 'senate_health_care_bill' => 'bill#text', :id => '111-h3590', :version => 'ocas'
  match 'house_reconciliation' => 'index#house_reconciliation'
  match 'pipa' => 'index#pipa'

  match ':controller(/:action(/:id))'
  #match '*path' => 'index#notfound' #unless Rails.application.config.consider_all_requests_local
  
end  

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User", :foreign_key => "friend_id"

  def confirm
    @confirmed = true
    update_attributes!({:confirmed => true, :confirmed_at => Time.new})
  end

  def recently_confirmed?
    @confirmed
  end
  
  def self.recent_activity(friends)
    ra = []
    number_of_friends = friends.length
    range = [0..3]
    case number_of_friends
    when 1
      friends.each do |f|
        ra.concat(f.friend.recent_public_actions(12)[0..11])
      end
    when 2
      friends.each do |f|
        ra.concat(f.friend.recent_public_actions(6)[0..5])
      end
    else
      friends.each do |f|
        ra.concat(f.friend.recent_public_actions(4)[0..3])
      end
    end

    ra.compact.sort_by{|p| p.created_at}.reverse
  end

  def self.create_confirmed_friendship(u1, u2)
    Friend.create({:friend_id => u1.id, :user_id => u2.id, :confirmed => true, :confirmed_at => Time.new})
    Friend.create({:friend_id => u2.id, :user_id => u1.id, :confirmed => true, :confirmed_at => Time.new})
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
  
  def user_name(pronoun,extras)
		if @user == current_user
			use_name = "#{pronoun}"
		else
 			use_name = @user.login + "#{extras}"
		end
	end
end

app/views/friends/_tracking_tables.html.erb
  <% if @in_my_district_solr && @in_my_district_solr.total > 0 %>
    <h3>In My Congressional District</h3>
    <%= render :partial => "tracking_table", :locals => {:collection => @in_my_district} %>
    <br/>
  <% end %>

  <% if @in_my_state_solr && @in_my_state_solr.total > 0 %>
    <h3>In <%= @state_name %></h3>
    <%= render :partial => "tracking_table", :locals => {:collection => @in_my_state} %>
    <br/>
  <% end %>
  
  <h3>All Users</h3>

  <%= render :partial => "tracking_table", :locals => {:collection => @users} %>

app/views/friends/index.html.erb
<div id="heading">
  <h2><%= @user.login %>'s Friends</h2>

</div>


<div class="container_16">

<div class="space clear">&nbsp;</div>

<% if @user.can_view(:my_friends, current_user) %>

<div class="space clear">&nbsp;</div>




<div class="grid_10"> 
  <h2>Most active users in my state and Congressional district</h2>

  <% if controller.controller_name == "friends" %>
    <% if @user == current_user %>
    
    
    
  <div class="invites">
  
  	<script type='text/javascript'>
  	$j().ready(function() {
  		$j('#invite_form').jqm({ajax:'@href', trigger: 'a.invite_trigger'});
  	});
  	</script>  
    
    <ul>
      <li><%= link_to "See users in my state and district", friends_near_me_path(@user.login), :class => '' %></li>
      
      <li><%= link_to 'Find users by e-mail, username, or real name', new_friend_path(@user.login), :class => '' %></li>
      
      <li><%= link_to "Import friends from G-Mail, Yahoo!, or Hotmail", friends_import_contacts_path, :class => '' %></li>
      
      <li><%= link_to "Invite more friends to join OpenCongress!", 
              friends_invite_form_path(current_user.login), 
              :class => "invite_trigger" %></li>
    </ul>
   
  	<div class="form" id="invite_friend" style="display:none; margin-top:10px;">
      <%= render :partial => 'invite_form' %>
      </div>
     <div style="clear:both;"></div>
    </div>
    <div id="invite_form" class="jqmWindow"></div>
    <% end %>   
  <% end %>



<div class="space clear">&nbsp;</div>
<div class="space clear">&nbsp;</div>






  <h3>Friend requests pending your approval</h3>

  <div class="grid_9 alpha">
    <div class="grid_2 alpha">
  
    <% for friend in @fans %>
    	
    	<strong><%=link_to h(friend.user.login), user_profile_path(friend.user.login) %></strong>
   
   
    </div>
        
        
    <div class="grid_3 omega">
        <%=h friend.user.location && !friend.user.location.empty? ? friend.user.location : "[Not Public]" %>
        <% zd = ZipcodeDistrict.zip_lookup(friend.user.zipcode, (friend.user.zip_four ? friend.user.zip_four : nil)).first %>
        
        
        <%=h zd.state + "-" if zd %>
        <%=h zd.district if zd %>
    </div>
  
  
    <div class="grid_3 alpha">
  
  
 		
  		<%= button_to('Decline', friends_add_deny_path(friend.friend.login,friend.user), :confirm => 'Are you sure?') unless @user != current_user %></td>
  		
  		<%= button_to('Accept', friends_add_confirm_path(friend.friend.login,friend.user), :confirm => 'Are you sure?') unless @user != current_user %></td>
  

  
  
  			<div id="coms_friend_<%= friend.id %>" style="display:none;"></div>
  			<div id="votes_friend_<%= friend.id %>" style="display:none;"></div>
  	
  	
    </div>
    
    <div class="grid_8 alpha">
  		<%= link_to "Tracked Items(#{friend.user.bookmarks.count})", {:controller => 'profile', :login => friend.user.login, :action => 'items_tracked'}, :class => 'button tiny silver' %></td>
  	 	
  	 	<%= link_to "Recent Actions", :controller => 'profile', :login => friend.user.login, :action => 'actions' %></td>
  		
  		<%= link_to h(friend.user.login) + "'s Political Notebook", :controller => 'political_notebooks', :login => friend.user.login, :action => 'show' %></td>  		
  	 
     </div>
    
  </div>

	<% end %>






<% if @friends.length > 0 %>
<div class="space clear">&nbsp;</div>
<div class="space clear">&nbsp;</div>
<div class="space clear">&nbsp;</div>

<div class="space clear">&nbsp;</div>
<div class="clear padding-top">
<h3 class="inline"><%= user_name("My", "'s") %> Friends</h3>

<% if @user == current_user %>
	<span style="margin:2px 5px 0 20px;float:left;"><%= image_tag("private.png", :alt => "private", :title => "Private") %></span>
		<% form_for :privacy_option, @user.privacy_option, :url => {:controller => "/profile", :action => 'update_privacy' } do |f| %>
		  <%= f.select PrivacyOption.column_names[11].to_sym, [["Public",2],["Friends", 1], ["Private",0]], {}, {:onchange => "this.form.submit();"} %>
		<% end %>
<% end %>
<div class="clearfix"></div>

	<% @friends.each do |friend| %>  
<div class="<%= cycle('friendly','friendly one','friendly two') %>">
	<div class="remove"><% link_to('X', friend_path(@user.login,friend), :confirm => 'Remove ' + friend.friend.login + ' from your friends? Please confirm.', :method => :delete, :class => "x") unless @user != current_user %></div>

	<div style="background:#f5f7fa;padding:5px;">
					<div style="position:relative;">
					<div style="position:absolute;top:0;right:0;">
					  <%= link_to('Remove Friend', friend_path(@user.login,friend), :method => :delete) unless @user != current_user %>
					</div>
					</div>
					<table  cellspacing="0">
						<tr>
							<% if friend.friend.main_picture %>
							<td><%= image_tag "#{Settings.base_url}images/users/" + friend.friend.login + "_m.jpg", :alt => friend.friend.login %></td>
							<% else %>
							<td><%= image_tag "anonymous.gif", :alt => "No Picture" %></td>
							<% end %>
							<td style="padding-left:15px;">
								<table>
							<% unless friend.friend.location.nil? %>
								<% unless friend.friend.location.empty? %>
							<tr>
								<td><%= h friend.friend.location %>,<% end %>
								<% if friend.confirmed %>
								  <% if friend.friend.zipcode %>
								    <% zd = ZipcodeDistrict.zip_lookup(friend.friend.zipcode, (friend.friend.zip_four ? friend.friend.zip_four : nil)).first %>
								  <% end %>
								  <% if zd %>
								  &nbsp;District: (<%=h zd.state + "-" %><%=h zd.district%>)</td>
                  <% end %>
								<% end %>
							<% end %>
							<% if friend.confirmed %>

							<% if friend.friend.homepage && friend.friend.show_homepage == true %>
							<tr>
								<td><%=h friend.friend.homepage %></td>
							</tr>	
							<% end %>
							<tr>
								<td><%= link_to "Items Tracked(#{friend.friend.bookmarks.count})", :controller => 'profile', :login => friend.friend.login, :action => 'items_tracked' %></td>
							</tr>
							<% end %>
							</table>
						</td>
						</tr>
						<tr>
							<td style="text-align:center;"><%= link_to h(friend.friend.login), user_profile_path(friend.friend.login) %></td>
							<td style="padding:0px 15px;"><%= link_to "Recent Actions", :controller => 'profile', :login => friend.friend.login, :action => 'actions' %></td>
							<td><%= link_to h(friend.friend.login) + "'s Political Notebook", :controller => 'political_notebooks', :login => friend.friend.login, :action => 'show' %></td>
						</tr>
					</table>
					<div class="update_text" id="coms_friend_<%= friend.id %>" style="display:none;margin-top:1em;"></div>
					<div class="update_text" id="votes_friend_<%= friend.id %>" style="display:none;margin-top:1em;"></div>
				</div>
			</div>
				<% end %>
			<% end %>

	</div>

</div>

<% else %>
<p>Not Publicly Viewable</p>
<% end %>


  </div>

  </div>


<div id="the-items" class="friends grid_6">
      <% if @friends.length < 1 %>
    <p><%= user_name("You have", " has") %> not yet added any friends.</p>
    
    <% else %>
    
  
  
  
    <h3><!--<%= user_name("My", "'s") %>--> Recent Friends Activity</h3>
    <ul class="activity">
    	<% @recent_friends_ativity.each do |ra| %>
         <%= render :partial => "recent_list_items", :locals => {:ra => ra} %>
    	<% end %>
    </ul>
    <ul id="more_f_activity" class="activity" style="display:none;width:100%;">
    	<% @more_recent_friends_activity.each do |ra| %>
         <%= render :partial => "recent_list_items", :locals => {:ra => ra} %>
    	<li><%= link_to h(ra.user.login), user_profile_path(ra.user.login) %>  
    		<% if ra.class.to_s == "BillVote" %>
    		voted <b><%= ra.support == 0 ? "for" : "against" %></b>
    		<%= link_to(ra.bill.typenumber, bill_path(ra.bill)) %>
    		<% elsif ra.class.to_s == "Comment" %>
    		<% if ra.commentable_type == "Bill" %>
    		commented on <%= link_to(ra.bill.typenumber, bill_path(ra.bill)) %>
    		<% elsif ra.commentable_type == "Person" %>
    		commented on <%= link_to ra.person.name, person_url(ra.person.ident) %>
    		<% end %>
    		<% end %>
    		about <%= time_ago_in_words(ra.created_at) %> ago
    	</li>
    	<% end if @more_recent_friends_activity %>
    </ul>
    <% if @more_recent_friends_activity %>
    	<p class="line">
    	   <%= toggler("more_f_activity", "Show More Activity", "Hide Extra Activity", "arrow", "arrow-hide")%>
      </p>
    <% end %>
  
    <% end %>
  </div>

  <% unless @fans.length == 0 %>










<% end %>
</div>

app/views/friends/invite_contacts.html.erb
   <%= render :partial => "/profile/logged_in_profile_nav" %>
<h1>Friends Invited</h1>
<p>Your friends have been invited.  They should be receiving an invitation email shortly.  Once they accept your invitation, you will automatically be "OpenCongress Friends".
  </p>
  <h3>Invited:</h3>
  <ul>
  <% @results.each do |r| %>
    <li><%= r %></li>
  <% end %>
  </ul>

app/views/friends/new.html.erb
<%= render :partial => "profile/profile_nav" %>

<div class="profile_content">



<h1>Add a friend</h1>


<div style="margin:10px 20px 0 0;clear:both;float:left;">
<h3>Find Users</h3>
<ul style="margin-left:10px;">
<li><%= toggler("find_by_email", "By Email", "Hide&nbsp;Details", "arrow big", "arrow-hide big" ) %> </li>
<li><%= toggler("find_by_name", "By Real Name", "Hide&nbsp;Details", "arrow big", "arrow-hide big" )%> </li>
<li><%= toggler("find_by_username", "By Username", "Hide&nbsp;Details", "arrow big", "arrow-hide big" )%> </li>
</ul>
</div>


<div id="find_by_email" style="display:none;float:left;margin-top:20px;">
	<fieldset style="border:0;"><legend>Find User by Email</legend>
	   <% form_remote_tag :update => "resdiv", :url => {:action => 'search'} do %>
	     <input type="text" name="email" />
	     <%= submit_tag "Search" %>
	    <% end %>
	</fieldset>
</div>
<div id="find_by_name" style="display:none;float:left;margin-top:20px;">
	<fieldset style="border:0;"><legend>Find User by Real Name</legend>
	   <% form_remote_tag :update => "resdiv", :url => {:action => 'search'} do %>
	     <input type="text" name="name" />
	     <%= submit_tag "Search" %>
	    <% end %>
	</fieldset>
</div>
<div id="find_by_username" style="display:none;float:left;margin-top:20px;">
	<fieldset style="border:0;"><legend>Find User by Username</legend>
	   <% form_remote_tag :update => "resdiv", :url => {:action => 'search'} do %>
	     <input type="text" name="login" />
	     <%= submit_tag "Search" %>
	    <% end %>
	</fieldset>
</div>
<div id="resdiv" style="clear:both;padding-top:10px;"></div>

</div>

app/views/friends/opposing_bill.html.erb
<div class="explain_box">
This is a list of all the users opposing <%= @bill.typenumber %> who have made their pages of Tracked Items public. Some users may be opposing <%= @bill.typenumber %>, but have made their pages private or friends-only. For more info, click on the usernames below and view their profile pages of Actions. You may find people with expertise in your interests or opinions that you value. Invite them to be your friend, and their latest actions will appear in your profile's page of Friends.  
</div>

<% if @users.empty? %>
  <p>Nobody is opposing that Bill</p>
<% else %>

<table style="border:2px solid #EEF2EB;background:#FEFCEC none repeat scroll 0%;width:100%;">
<tr>
  <% if @in_my_district_solr && @in_my_district_solr.total > 0 %>
  <th>Users in My District Opposing <%= @bill.typenumber %>: <%= @in_my_district.length %> 
     <br/><span style="font-weight:normal;">(<%= @in_my_district.collect{|u| u['support'] == "0" ? 1 : nil }.compact.length %> votes Aye, <%= @in_my_district.collect{|u| u['support'] == "1" ? 1 : nil }.compact.length %> votes Nay, <%= @in_my_district.sum{|k| k['total_comments'].to_i} %> comments)</span>
  </th>
  <% end %>
  <% if @in_my_state_solr && @in_my_state_solr.total > 0 %>
  <th>Users in My State Opposing <%= @bill.typenumber %>: <%= @in_my_state.length %>
     <br/><span style="font-weight:normal;">(<%= @in_my_state.collect{|u| u['support'] == "0" ? 1 : nil }.compact.length %> votes Aye, <%= @in_my_state.collect{|u| u['support'] == "1" ? 1 : nil }.compact.length %> votes Nay, <%= @in_my_state.sum{|k| k['total_comments'].to_i} %> comments)</span>
  </th>
  <% end %>
<% if @users_solr && @users_solr.total > 0 %>
<th>All Users Opposing <%= @bill.typenumber %>: <%= @users.length %>
   <br/><span style="font-weight:normal;">(<%= @users.collect{|u| u['support'] == "0" ? 1 : nil }.compact.length %> votes Aye, <%= @users.collect{|u| u['support'] == "1" ? 1 : nil }.compact.length %> votes Nay, <%= @users.sum{|k| k['total_comments'].to_i} %> comments)</span>
</th>
<% end %>

</tr>
</table> 
<br/>
  <%= render :partial => "tracking_tables" %>

<% end %>
  

app/views/friends/search.html.erb
<div style="border:1px solid #E3E7DF;padding:3px 5px;background:#f5f7fa;">

	<div style="padding:10px;background:#fff;"><h3>Search Results</h3>
<% if @results.length == 0 %>
Sorry, nothing found.
<% else %>

<ul>
  <% @results.each do |r| %>
    <li><%= link_to h(r.login), user_profile_path(r.login) %> <span id="fdiv_<%=h r.id %>"><%= add_friend_link_ajax(r, "fdiv_#{r.id}") %></span></li>
  <% end %>
</ul>

<% end %>
	</div>
</div>

app/views/friends/show.html.erb
<% if logged_in? %>
   <%= render :partial => "/profile/logged_in_profile_nav" %>
<% end %>
<p>
  <b>User:</b>
  <%=h @friend.user_id %>
</p>

<p>
  <b>Friend:</b>
  <%=h @friend.friend_id %>
</p>

<p>
  <b>Confirmed:</b>
  <%=h @friend.confirmed %>
</p>

<p>
  <b>Created at:</b>
  <%=h @friend.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%=h @friend.updated_at %>
</p>

<p>
  <b>Confirmed at:</b>
  <%=h @friend.confirmed_at %>
</p>


<%= link_to 'Edit', edit_friend_path(@user.login,@friend) %> |
<%= link_to 'Back', friends_path(@user.login) %>

app/views/friends/show_recent_comments.html.erb
<% if @coms.length == 0 %>
<p>No Recent Comments</p>
<% end %>
<% @coms.each do |com| %>
<%= render :partial => "/profile/comment", :locals => {:comment => com} %>
<% end %>

app/views/friends/show_recent_votes.html.erb
<% if @votes.length == 0 %>
  <p>No Recent Votes</p>
<% end %>
<% @votes.each do |v| %>
<% bill = v.bill %>
          <%= v.support == 0 ? "Supporting: " : "Opposing: " %>
          <%= link_to bill.typenumber, bill_path(bill) %>
          <%= bill.title_common %></span>
        <br/>
<% end %>

app/views/friends/tracking_committee.html.erb
<div id="heading">
	<div class="explain_box">
This is a list of all the users tracking <%= @committee.name %> who have made their pages of Tracked Items public. Some users may be tracking <%= @committee.name %>, but have made their pages private or friends-only. For more info, click on the usernames below and view their profile pages of Actions. You may find people with expertise in your interests or opinions that you value. Invite them to be your friend, and their latest actions will appear in your profile's page of Friends.  
</div>
</div>
<div class="padding">
<% if @users.empty? %>
  <p>Nobody is tracking that Committee</p>
<% else %>

  <%= render :partial => "tracking_tables" %>

<% end %>
</div>

app/views/friends/user_mailing_lists.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>UserMailingLists: <%= controller.action_name %></title>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield %>

</body>
</html>