config/routes.rb
OpenCongress::Application.routes.draw do
  # API
  constraints :subdomain => 'api' do
    match '/' => redirect(Settings.base_url + 'api')
    match '/bill/text_summary/:id' => 'bill#status_text'
    match '/roll_call/text_summary/:id' => 'roll_call#summary_text'
    with_options :format => [:json, :xml] do |f|
      f.match '/groups(.:format)' => 'groups#index'
      f.match '/groups(/:id(.:format))' => 'groups#show'
    end
    match '/:action(/:id)', :controller => 'api'
  end

  resources :mailing_list_items
  resources :watch_dogs

  resources :states do
    resources :districts
  end

  resources :groups do
    resources :group_invites
    resources :group_members
    resources :group_bill_positions
    
    resource :political_notebook do
      resources :notebook_items do
        collection do
          get :feed
        end
      end
      resources :notebook_links
      resources :notebook_videos
      resources :notebook_notes
      resources :notebook_files    
    end
  end
  
  resources :simple_captcha, :only => :show
  
  match '/' => 'index#index', :as => :home

  # Allow downloading Web Service WSDL as a file with an extension
  # instead of a file named 'wsdl'
  # match ':controller/service.wsdl' => 'wsdl'

  # Handle bill routing. The action determines what information about the bill will 
  # be displayed.
  match 'bill/:id/users_tracking' => 'friends#tracking_bill', :as => :users_tracking_bill
  match 'bill/:id/users_tracking/:state' => 'friends#tracking_bill', :state => /\w{2}/, :as => :users_tracking_bill_by_state

  scope 'bill', :controller => 'bill' do
    for action in %w{ all pending popular major hot readthebill compare compare_by_issues atom_top20 }
      match action, :action => action, :as => 'bill_' + action
    end

    match 'most/:type', :action => 'most_commentary', :as => :bill_most_commentary
    match 'most/viewed', :action => 'popular'
    match 'atom/most/viewed', :action => 'atom_top20'
    match 'atom/most/:type', :action => 'atom_top_commentary'
    match 'type/:bill_type(/:page)', :action => 'list_bill_type'
    match 'text/status/:id', :action => 'status_text'
    match 'upcoming/:id', :action => 'upcoming'
    match 'bill_vote/:bill/:id', :action => 'bill_vote'

    scope ':id' do
      match 'blogs(/:page)', :action => 'blogs', :as => :blogs_bill
      match 'blogs/search(/:page)', :action => 'commentary_search', :commentary_type => 'blog'        
      match 'news(/:page)', :action => 'news', :as => :news_bill
      match 'news/search(/:page)', :action => 'commentary_search', :commentary_type => 'news'        
      match 'text', :action => 'text', :as => :bill_text
      match 'comments', :action => 'comments', :as => :bill_comments
      match 'show', :action => 'show', :as => :bill
      match ':action'
    end

    match ':id' => 'bill#show'

  end
  match 'bill' => redirect('/bill/all')

  scope 'people', :controller => 'people' do
    match 'senators', :action => 'people_list', :person_type => 'senators'
    match 'representatives', :action => 'people_list', :person_type => 'representatives'
    match ':person_type/most/:type', :action => 'most_commentary'
    match ':person_type/atom/most/:type', :action => 'atom_top_commentary'
    match 'atom/featured', :action => 'atom_featured'
    match 'wiki/:id', :action => 'wiki'
    match 'comments/:id', :action => 'comments'
    match 'news/:id(/:page)', :action => 'news', :as => :news_person
    match 'blogs/:id(/:page)', :action => 'blogs', :as => :blogs_person
    match 'votes_with_party/:chamber/:party', :action => 'votes_with_party'
    match 'voting_history/:id/:page', :action => 'voting_history'
    match 'compare.:format', :action => 'compare'
    match 'show/:id', :action => 'show', :as => 'person'
  end

  match 'person/*path' => redirect("/people/%{path}")

  namespace :admin do
     resources :wiki_links, :pvs_category_mappings, :talking_points
     resources :articles do
       collection do
         get :list
         get :edit_blogroll
       end
       resources :article_images
     end

     match '/' => 'index#index', :as => 'admin'
     
     scope 'stats', :controller => 'stats' do
       match 'bills.:format', :action => 'bills'
       match 'partner_email.:format', :action => 'partner_email'
     end
     
     match 'contact_congress' => 'contact_congress#index'
     match 'contact_congress/letters' => 'contact_congress#letters'
  end
  match '/:controller(/:action(/:id))', :controller => /admin\/[^\/]+/
  

  match 'battle_royale' => 'battle_royale#index'
  match 'battle_royale/:action', :controller => 'battle_royale'

  match 'blog(/:tag)' => 'articles#list', :as => :blogs
  
  scope 'articles', :controller => 'articles' do
    match 'view/:id', :action => 'view', :as => :article
    match ':id/atom', :action => 'article_atom'
  end

  match 'issues' => 'issue#index'

  scope 'issues', :controller => 'issue' do
    match 'show/:id', :action => 'show', :as => :issue
    match ':action/:id'
  end

  
  #######TEMP REMOVE
  # scope :module => 'formageddon', :as => 'formageddon' do    
  #   resources :formageddon_threads, :controller => 'threads', :path => '/formageddon/threads'
  #   resources :formageddon_contact_steps, :controller => 'contact_steps', :path => '/formageddon/contact_steps'
  # end
  # 
  # 
  # 
  # 
  # 
  # # Install the default route as the lowest priority.
  # map.connect ':controller/:action/:id'
  

  resources :contact_congress_letters, :only => [:index, :show, :new, :update] do
    get 'create_from_formageddon', :on => :collection # create uses POST and we'll be redirecting to create
    get 'get_recipients', :on => :collection 
    get 'delayed_send', :on => :collection
    get 'get_replies', :on => :collection
  end
  
  match 'howtouse' => 'about#howtouse'
  
  scope :controller => 'account' do
    for action in %w{ login why logout signup welcome contact_congress}
      match action, :action => action
    end
    
    match 'register', :action => 'signup'
    match 'account/confirm/:login', :action => 'confirm'
  end

  scope :controller => 'comments' do
    match 'comments/all_comments/:object/:id', :action => 'all_comments'
    match 'comments/atom/:object/:id', :action => 'atom_comments'
  end

  match 'users/:login/profile' => 'profile#show', :as => :user_profile

  scope 'users/:login' do

    scope 'profile' do 
      resource :political_notebook do
        collection do
          post :update_privacy
          get :feed
        end
        resources :notebook_links do
          collection do
            get :faceform
          end
        end
        resources :notebook_videos
        resources :notebook_notes
        resources :notebook_files    
      end
    
      scope 'friends', :controller => 'friends' do
        for action in %w{ import_contacts like_voters invite_contacts near_me invite invite_form }
          match action, :action => action, :as => 'friends_' + action
        end

        for action in %w{ confirm deny } do
          match action + '/:id', :action => action, :as => 'friends_add_' + action
        end
      end
  
      resources :friends

      scope :controller => 'profile' do
        for action in %w{ actions items_tracked watchdog edit_profile bills_supported tracked_rss user_actions_rss bills_opposed my_votes bills comments issues committees groups } do
          match action, :action => action, :as => 'user_' + action
        end

        match ':person_type', :action => 'person'
      end
    end # profile
    
    match 'feeds/:action(/:key)', :controller => 'user_feeds'
    
  end # users/:login

  match 'video/rss' => 'video#all', :format => 'atom'

  scope :controller => 'roll_call' do
    match 'roll_call/text/summary/:id', :action => 'summary_text'      
    match 'vote/:year/:chamber/:number(/:state)', :action => 'by_number', :year => /\d{4}/, :chamber => /[hs]/, :number => /\d+/, :state => /\w{2}/
  end

  match 'tools(/:action(/:id))', :controller => 'resources', :as => 'tools'

  match '/widgets' => 'widgets#index', :as => 'widgets'
  match '/widgets/deprecated' => 'widgets#deprecated', :as => 'deprecated_widgets'
  match '/widgets/bill' => 'widgets#bill', :as => 'bill_widget'
  match '/widgets/bills' => 'widgets#bills', :as => 'bills_widget'
  match '/widgets/people' => 'widgets#people', :as => 'people_widget'
  match '/widgets/group' => 'widgets#group', :as => 'group_widget'

  match 'api' => 'api#index'
  match 'api/bill/text_summary/:id' => 'bill#status_text'
  match 'api/roll_call/text_summary/:id' => 'roll_call#summary_text'
  match 'api(/:action(/:id)(.:format))', :controller => 'api'

  # Temporary routes for health care legislation
  match 'baucus_bill_health_care.html' => 'index#s1796_redirect'
  match 'presidents_health_care_proposal' => 'index#presidents_health_care_proposal'
  match 'senate_health_care_bill' => 'bill#text', :id => '111-h3590', :version => 'ocas'
  match 'house_reconciliation' => 'index#house_reconciliation'
  match 'pipa' => 'index#pipa'

  match ':controller(/:action(/:id))'
  #match '*path' => 'index#notfound' #unless Rails.application.config.consider_all_requests_local
  
end  

app/views/resources/_panel_colors_form.html.erb
<dt><label for="post_info_url">Background color:</label></dt>
<dd><%= select("panel", "bgcolor_select", available_colors, { :selected => "ffffff" }, { :onChange => "#{update_function}('panel_bgcolor');" }) %><br>
    <div class="form_note">Or, enter the six-digit hex code:
<%= text_field 'panel', 'bgcolor', { :size => '6', :maxlength => '6', :value => "ffffff" } %></div></dd>

<dt><label for="post_info_url">Border color:</label></dt>
<dd><%= select("panel", "bordercolor_select", available_colors, { :selected => "999999" }, { :onChange => "#{update_function}('panel_bordercolor');" }) %><br>
    <div class="form_note">Or, enter the six-digit hex code:
<%= text_field 'panel', 'bordercolor', { :size => '6', :maxlength => '6', :value => "999999" } %></div></dd>

<dt><label for="post_info_url">Text color:</label></dt>
<dd><%= select("panel", "textcolor_select", available_colors, { :selected => "333333" }, { :onChange => "#{update_function}('panel_textcolor');" }) %><br>
    <div class="form_note">Or, enter the six-digit hex code:
<%= text_field 'panel', 'textcolor', { :size => '6', :maxlength => '6', :value => "333333" } %></div></dd>

app/views/resources/bill_status_panel.html.erb
<html>
  <head>
    <style>
      html { font-size:100.01%; /* fixes some browser bugs */ }
      
      body {
      	font:1em "Trebuchet MS",Verdana,Arial,Helvetica,sans-serif;
      	background: #<%= @bgcolor %>;
      	color: #<%= @textcolor %>;
      }
    
      #bill_status {
        font-size: 12px;
      }
#bill_status ul {
	margin-bottom:10px;
}
#title, #links, #powered {
	text-align:center;
	line-height:1.1em;
}
#title h1 {
	font-size:14px;
	font-weight:bold;
	margin:5px 5px 0 5px;
}
#title p {
	margin-top:4px;
}
#links {
	margin-bottom:5px;
}
#powered {
	font-size:10px;
	margin-bottom:3px;
}
	a {
        color: #<%= @textcolor %>;
      }
      a:hover {
        text-decoration: none;
      }
      ul {
        list-style: none;
        margin: 0;
        padding: 0;
      }
    
      li {
        margin: 0 5px 2px 5px;
        line-height: 14px;
      }
    </style>
  </head>

  <body>
    <% if @bill %>
      <div id="bill_status">
        <div class="syndicator_items">		
			<div id="title">
            	<h1><%= @bill.typenumber %> <a href="/bill/<%= @bill.ident %>/atom" target="_top"><%= image_tag 'feed-icon-10x10.png', :border => '0' %></a></h1>

				<p><%= @bill.title_common %></p>
			</div>
	        	<ul>
	            <li><strong>Introduced:</strong> <%= Time.at(@bill.introduced).strftime("%B %d, %Y") %></li>
	            <li><strong>Status:</strong> <%= @bill.status %></li>
	            <% if @bill.next_step %><li><strong>Next step:</strong> <%= @bill.next_step %></li><% end %>
	            <li><strong>Latest action:</strong> <%= @bill.last_action.text %></li>
	            <li><strong>Sponsor:</strong> <%= @bill.sponsor.name %></li>
	      		</ul>
			<div id="links">
            	<%= link_to 'View Bill >>', bill_path(@bill), :target => '_top' %><br />
	            <%= link_to 'News Coverage', news_bill_path(@bill), :target => '_top' %> | 
	            <%= link_to 'Blog Coverage', blogs_bill_path(@bill), :target => '_top' %>
			</div>
			<div id="powered">
	            	<span>Powered by <%= link_to 'OpenCongress', home_url, :target => '_top' %></span>
			</div>
      	</div>
	</div>
    <% else %>
      There is an error.
    <% end %>
  </body>
</html>

app/views/resources/climate_change_panel.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><%= @page_title %></title>

	<style media="all" type="text/css">

.climate_change_widget {
   background: url(<%= image_path 'widgets/climate_bg.png' %>) left 0 no-repeat;
   width: 320px;
   font-family: Arial, Helvetica, sans-serif;
   padding: 0px;
   font-size: 12px;
}


.climate_change_widget a{
color: #333;
}

.climate_change_widget .title {
   border-bottom: 1px solid #999;
   min-height: 69px;
}

.climate_change_widget .title h3 {
   margin: 0;
   font-size: 15px;
   color: #136b9e;
   padding: 18px 0 0 68px;
}


.climate_change_widget .title p {
   margin: 0;
   padding: 2px 0 0 68px;
   font-size: 11px;
}


.climate_change_widget .guts {
   border-left: 1px solid #999;
   border-right: 1px solid #999;
   padding: 15px 15px 0;
      background: #fff url(<%= image_path 'widgets/climate_bg.png' %>) -1px -70px no-repeat;

}

.climate_change_widget .guts h4 {
   margin: 0;
   padding: 0 0 10px 0;
   font-size: 11px;
   color: #136b9e;
}

.climate_change_widget .house {
   border-bottom: 1px solid #ddd;
   padding-bottom: 15px;
}

.climate_change_widget .senate {
   margin-top: 15px;
   border-bottom: 1px solid #ddd;
   padding-bottom: 15px;
}

.climate_change_widget .senate .status {
   padding: 15px;
   background: #e9f2e4;
}

.climate_change_widget .senate .status h5 {
   margin: 0 0 10px 0;
   font-size: 12px;
   color: #49643c;
}

.climate_change_widget .blog_coverage {
   display: block;
   background: url(<%= image_path 'widgets/button-320.png' %>) no-repeat;
   height: 40px;
   padding-top: 20px;
}

.climate_change_widget .blog_coverage a {
   display: block;
   color: #333;
   padding: 0 0 0 15px;
   font-weight: bold;
   font-size: 12px;
   text-decoration: none;
}

.blog_coverage a:hover, .climate_change_widget a:hover {
   color: #000;
}

.passed {
   color: #4a862a;
   padding-left: 23px;
   background: url(<%= image_path 'widgets/widget_icons.png' %>) 7px -114px no-repeat;
}

.introduced {
   padding-left: 10px;
   color: #ccc;
}

.full_text, .comments, .roll_call, .voting_record, .tracking {
   background: url(<%= image_path 'widgets/widget_icons.png' %>) 0 14px no-repeat;
   padding-left: 18px;
   line-height: 1.8em;
   color: #555;
   float: left;
}

.full_text {
padding-top: 10px;
}

.pres_bill {
   background: url(<%= image_path 'widgets/widget_icons.png' %>) 0 5px no-repeat;
clear: both;
margin-bottom: 0px;
display: block;
padding-left: 16px;
line-height: 2em;
}




.comments {
   background-position: 0 -84px;
}

.roll_call {
   background-position: 0 -27px;
   display: block;
   float: none;
   clear: both;
}


.voting_record {
   background-position: 1px -27px;
   display: block;
   float: none;
   clear: both;
}


.tracking {
   background-position: 0 -57px;
   display: block;
   float: none;
   clear: both;
}


.democrat {
   padding-left: 20px;
   background: url(<%= image_path 'widgets/widget_icons.png' %>) 0 -139px no-repeat;
}


.republican {
   padding-left: 20px;
   background: url(<%= image_path 'widgets/widget_icons.png' %>) 0 -168px no-repeat;
}

.status ul {
   padding: 0;
   margin: 0 0 10px 0;
}


.status ul li {
   margin-bottom: 3px;
   list-style: none;
}


h5.bill_title {
   margin: 0;
   font-size: 12px;
   margin-bottom: 10px;
}

h5.bill_title a:visited,
h5.bill_title a:link {
   color: black;
}


	</style>
</head>
<body>


<div class="climate_change_widget">
	<div class="title">
		<h3>Climate Change in Congress</h3>
		<% if @state_name %>
		   <p>What People in <strong><%= @state_name %></strong> Are Saying on <%= link_to "OpenCongress", home_url, :target => "_blank" %></p>
      <% else %>
         <p>What People Are Saying on <%= link_to "OpenCongress", home_url, :target => "_blank" %></p>
      <% end %>
	</div>

	<div class="guts">
		<div class="house">
			<h4>House Version: <a href="http://www.opencongress.org/bill/111-h2454/show">H.R.2454</a></h4>
			
			
				<h5 class="bill_title"><a href="http://www.opencongress.org/bill/111-h2454/show">American Clean Energy And Security Act of 2009</a></h5>
			
							<span>Latest Action: <span class="passed">Passed on June 26, 2009</span></span>
<span class="full_text"><a href="http://www.opencongress.org/bill/111-h2454/text">Read and comment on the bill text</a></span>

<span class="roll_call"><a href="http://www.opencongress.org/vote/2009/h/477">Full vote results (219-212)</a></span>
<span class="tracking"><a href="http://www.opencongress.org/bill/111-h2454/show#users_tracking">People watching this bill are also watching...</a></span>

		</div>

		<div class="senate">
			<h4>Senate Version <a href="http://www.opencongress.org/bill/111-s1733/show">S.1733</a></h4>
			
			<h5 class="bill_title"><a href="http://www.opencongress.org/bill/111-s1733/show">Clean Energy Jobs and American Power Act</a></h5>
   		
   		<span>Latest Action:  <span>Pending in Senate</span></span>
   		<span class="tracking"><a href="http://www.opencongress.org/bill/111-s1733/show#users_tracking">People watching this bill are also watching...</a></span> 
				</div>
		
		   </div> <!-- Guts -->
 <div class="blog_coverage">
   	<% if @state_name %>
   	<%= link_to "What's hot with people in your state?", state_url(params[:state]), :class => "hot", :target => "_blank" %>
      <% else %>
   	<%= link_to "What's hot with people in your state?", states_url, :class => "hot", :target => "_blank" %>
      <% end %>
   </div>
</div> <!-- End Widget -->

</body>
</html>

app/views/resources/healthcare_panel.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><%= @page_title %></title>

	<style media="all" type="text/css">

.healthcare_widget {
   background: url(<%= image_path 'widgets/healthcare_bg.png' %>) no-repeat;
   width: 320px;
   font-family: Arial, Helvetica, sans-serif;
   padding: 0px;
   font-size: 12px;
}


.healthcare_widget a{
color: #333;
}

.healthcare_widget .title {
   border-bottom: 1px solid #999;
   min-height: 69px;
}

.healthcare_widget .title h3 {
   margin: 0;
   font-size: 15px;
   color: #a82222;
   padding: 18px 0 0 68px;
}


.healthcare_widget .title p {
   margin: 0;
   padding: 2px 0 0 68px;
   font-size: 11px;
}


.healthcare_widget .guts {
   background: #fff url(<%= image_path 'widgets/healthcare_bg.png' %>) -1px -70px no-repeat;

   border-left: 1px solid #999;
   border-right: 1px solid #999;
   padding: 15px 15px 0;
}

.healthcare_widget .guts h4 {
   margin: 0;
   padding: 0 0 10px 0;
   font-size: 11px;
   color: #136b9e;
}

.healthcare_widget .house {
   border-bottom: 1px solid #ddd;
   padding-bottom: 15px;
}

.healthcare_widget .senate {
   margin-top: 15px;
   border-bottom: 1px solid #ddd;
   padding-bottom: 15px;
}

.healthcare_widget .senate .status {
   padding: 15px;
   background: #e9f2e4;
}

.healthcare_widget .senate .status h5 {
   margin: 0 0 10px 0;
   font-size: 12px;
   color: #49643c;
}

.healthcare_widget .blog_coverage {
   display: block;
   background: url(<%= image_path 'widgets/button-320.png' %>) no-repeat;
   height: 40px;
   width: 320px;
   padding-top: 20px;
}

.healthcare_widget .blog_coverage a {
   display: block;
   color: #333;
   padding: 0 0 0 15px;
   font-weight: bold;
   font-size: 12px;
   text-decoration: none;
}

.blog_coverage a:hover, .healthcare_widget a:hover {
   color: #000;
}

.passed {
   color: #4a862a;
   padding-left: 23px;
   background: url(<%= image_path 'widgets/widget_icons.png' %>) 7px -114px no-repeat;
}

.introduced {
   padding-left: 10px;
   color: #ccc;
}

.full_text, .comments, .roll_call, .voting_record, .tracking {
   background: url(<%= image_path 'widgets/widget_icons.png' %>) 0 14px no-repeat;
   padding-left: 18px;
   line-height: 1.8em;
   color: #555;
   float: left;
}

.full_text {
padding-top: 10px;
}

.pres_bill {
   background: url(<%= image_path 'widgets/widget_icons.png' %>) 0 5px no-repeat;
clear: both;
margin-bottom: 0px;
display: block;
padding-left: 16px;
line-height: 2em;
}




.comments {
   background-position: 0 -84px;
}

.roll_call {
   background-position: 0 -27px;
   display: block;
   float: none;
   clear: both;
}


.voting_record {
   background-position: 1px -27px;
   display: block;
   float: none;
   clear: both;
}


.tracking {
   background-position: 0 -57px;
   display: block;
   float: none;
   clear: both;
}


.democrat {
   padding-left: 20px;
   background: url(<%= image_path 'widgets/widget_icons.png' %>) 0 -139px no-repeat;
}


.republican {
   padding-left: 20px;
   background: url(<%= image_path 'widgets/widget_icons.png' %>) 0 -168px no-repeat;
}

.status ul {
   padding: 0;
   margin: 0 0 10px 0;
}


.status ul li {
   margin-bottom: 3px;
   list-style: none;
}


h5.bill_title {
   margin: 0;
   font-size: 12px;
   margin-bottom: 10px;
}

h5.bill_title a:visited,
h5.bill_title a:link {
   color: black;
}


	</style>
</head>
<body>


<div class="healthcare_widget">
	<div class="title">
		<h3>Health Care Reform in Congress</h3>
		<% if @state_name %>
		   <p>What People in <strong><%= @state_name %></strong> Are Saying on <%= link_to "OpenCongress", home_url, :target => "_blank" %></p>
      <% else %>
         <p>What People Are Saying on <%= link_to "OpenCongress", home_url, :target => "_blank" %></p>
      <% end %>
	</div>

	<div class="guts">
		<div class="house">
			<h4>House Version: <%= link_to "H.R. 3962", bill_url(@house_bill_ident), :target => "_blank" %></h4>
			
			
				<h5 class="bill_title"><%= link_to "Affordable Health Care for America Act", bill_url(@house_bill_ident), :target => "_blank" %></h5>
			
							<span>Latest Action: <span class="passed">Passed on Nov. 7, 2009</span></span>

			
<%= link_to("Read and comment on the bill text", url_for(:controller => 'bill', :action => 'text', :id => @house_bill_ident, :anchor => 'most_commented'), :class => "full_text", :target => "_blank") %>   			<%= link_to("Full vote result (220-215)", url_for(:controller => 'roll_call', :action => 'by_number', :year => "2009", :chamber => "h", :number => "887"), :class => "roll_call", :target => "_blank") %>
			<% if @state_name %>
   			<%= link_to("How #{ @state_name } Reps voted", url_for(:controller => 'roll_call', :action => 'by_number', :year => "2009", :chamber => "h", :number => "887", :state => params[:state]), :class => "voting_record", :target => "_blank") %>
         <% end %>
         <%= link_to("People watching this bill are also watching...", bill_url(@house_bill_ident, :anchor => "users_tracking"), :class => "tracking", :target => "_blank")%>

		</div>

		<div class="senate">
			<h4>Senate Version <%= link_to "H.R. 3590", bill_url(@senate_bill_ident), :target => "_blank" %></h4>
			
			<h5 class="bill_title"><%= link_to "Patient Protection and Affordable Care Act", bill_url(@senate_bill_ident), :target => "_blank" %></h5>
   		
   		<span>Latest Action:  <span class="passed">Passed on Dec. 24, 2009</span></span>
   		
   		<%= link_to("Read and comment on the bill text", url_for(:controller => 'bill', :action => 'text', :id => @senate_bill_ident, :anchor => 'most_commented'), :class => "full_text", :target => "_blank") %>   			
   			<%= link_to("Full vote result (60-39)", url_for(:controller => 'roll_call', :action => 'by_number', :year => "2009", :chamber => "s", :number => "396"), :class => "roll_call", :target => "_blank") %>
			<% if @state_name %>
   			<%= link_to("How #{ @state_name } Senators voted", url_for(:controller => 'roll_call', :action => 'by_number', :year => "2009", :chamber => "s", :number => "396", :state => params[:state]), :class => "voting_record", :target => "_blank") %>
		   <% end %>
		   <%= link_to("People watching this bill are also watching...", bill_url(@senate_bill_ident, :anchor => "users_tracking"), :class => "tracking", :target => "_blank")%>
				</div>

   			<div class="senate"> 
					<h5 class="bill_title"><a href="http://www.opencongress.org/bill/111-h4872/show" target="_blank">H.R. 4872 - Reconciliation Act of 2010</a></h5>
					<span>3/21/10: Passed House by a vote of 220-211</span>
					<a class="pres_bill" href="http://www.opencongress.org/house_reconciliation" target="_blank">Read the full bill text</a>
				</div>

   </div> <!-- Guts -->
   <div class="blog_coverage">
   	<% if @state_name %>
   	<%= link_to "What's hot with people in your state?", state_url(params[:state]), :class => "hot", :target => "_blank" %>
      <% else %>
   	<%= link_to "What's hot with people in your state?", states_url, :class => "hot", :target => "_blank" %>
      <% end %>
   </div>

</div> <!-- End Widget -->

</body>
</html>

app/views/resources/issue_search.html.erb
<% if @issues and !@issues.empty? %>
  Click on the issue to select it:<br />
  <% @issues.each do |i| %>
    <a href="javascript:setIssueBillsIssueId('<%= i.id %>')"><%= i.term %></a> 
    [<a href="/issue/show/<%= i.to_param %>" target="_blank">view issue</a>]<br />
  <% end %>
<% else %>
  No issues found.
<% end %>

<script type="text/javascript" language="javascript">
    // <![CDATA[
      new Effect.Highlight('search_results', {duration: 3});
    // ]]>
</script>

app/views/resources/subscribe_thanks.html.erb
<div id="heading">
  <h2>Your subscription is pending</h2>
</div>
<div class="padding">
  <p>
    Thanks! We've received your request. Check your inbox shortly for a confirmation email. If you do not see a confirmation email, please check your spam/junk mail folder.
  </p>
</div>