config/routes.rb
OpenCongress::Application.routes.draw do
  # API
  constraints :subdomain => 'api' do
    match '/' => redirect(Settings.base_url + 'api')
    match '/bill/text_summary/:id' => 'bill#status_text'
    match '/roll_call/text_summary/:id' => 'roll_call#summary_text'
    with_options :format => [:json, :xml] do |f|
      f.match '/groups(.:format)' => 'groups#index'
      f.match '/groups(/:id(.:format))' => 'groups#show'
    end
    match '/:action(/:id)', :controller => 'api'
  end

  resources :mailing_list_items
  resources :watch_dogs

  resources :states do
    resources :districts
  end

  resources :groups do
    resources :group_invites
    resources :group_members
    resources :group_bill_positions
    
    resource :political_notebook do
      resources :notebook_items do
        collection do
          get :feed
        end
      end
      resources :notebook_links
      resources :notebook_videos
      resources :notebook_notes
      resources :notebook_files    
    end
  end
  
  resources :simple_captcha, :only => :show
  
  match '/' => 'index#index', :as => :home

  # Allow downloading Web Service WSDL as a file with an extension
  # instead of a file named 'wsdl'
  # match ':controller/service.wsdl' => 'wsdl'

  # Handle bill routing. The action determines what information about the bill will 
  # be displayed.
  match 'bill/:id/users_tracking' => 'friends#tracking_bill', :as => :users_tracking_bill
  match 'bill/:id/users_tracking/:state' => 'friends#tracking_bill', :state => /\w{2}/, :as => :users_tracking_bill_by_state

  scope 'bill', :controller => 'bill' do
    for action in %w{ all pending popular major hot readthebill compare compare_by_issues atom_top20 }
      match action, :action => action, :as => 'bill_' + action
    end

    match 'most/:type', :action => 'most_commentary', :as => :bill_most_commentary
    match 'most/viewed', :action => 'popular'
    match 'atom/most/viewed', :action => 'atom_top20'
    match 'atom/most/:type', :action => 'atom_top_commentary'
    match 'type/:bill_type(/:page)', :action => 'list_bill_type'
    match 'text/status/:id', :action => 'status_text'
    match 'upcoming/:id', :action => 'upcoming'
    match 'bill_vote/:bill/:id', :action => 'bill_vote'

    scope ':id' do
      match 'blogs(/:page)', :action => 'blogs', :as => :blogs_bill
      match 'blogs/search(/:page)', :action => 'commentary_search', :commentary_type => 'blog'        
      match 'news(/:page)', :action => 'news', :as => :news_bill
      match 'news/search(/:page)', :action => 'commentary_search', :commentary_type => 'news'        
      match 'text', :action => 'text', :as => :bill_text
      match 'comments', :action => 'comments', :as => :bill_comments
      match 'show', :action => 'show', :as => :bill
      match ':action'
    end

    match ':id' => 'bill#show'

  end
  match 'bill' => redirect('/bill/all')

  scope 'people', :controller => 'people' do
    match 'senators', :action => 'people_list', :person_type => 'senators'
    match 'representatives', :action => 'people_list', :person_type => 'representatives'
    match ':person_type/most/:type', :action => 'most_commentary'
    match ':person_type/atom/most/:type', :action => 'atom_top_commentary'
    match 'atom/featured', :action => 'atom_featured'
    match 'wiki/:id', :action => 'wiki'
    match 'comments/:id', :action => 'comments'
    match 'news/:id(/:page)', :action => 'news', :as => :news_person
    match 'blogs/:id(/:page)', :action => 'blogs', :as => :blogs_person
    match 'votes_with_party/:chamber/:party', :action => 'votes_with_party'
    match 'voting_history/:id/:page', :action => 'voting_history'
    match 'compare.:format', :action => 'compare'
    match 'show/:id', :action => 'show', :as => 'person'
  end

  match 'person/*path' => redirect("/people/%{path}")

  namespace :admin do
     resources :wiki_links, :pvs_category_mappings, :talking_points
     resources :articles do
       collection do
         get :list
         get :edit_blogroll
       end
       resources :article_images
     end

     match '/' => 'index#index', :as => 'admin'
     
     scope 'stats', :controller => 'stats' do
       match 'bills.:format', :action => 'bills'
       match 'partner_email.:format', :action => 'partner_email'
     end
     
     match 'contact_congress' => 'contact_congress#index'
     match 'contact_congress/letters' => 'contact_congress#letters'
  end
  match '/:controller(/:action(/:id))', :controller => /admin\/[^\/]+/
  

  match 'battle_royale' => 'battle_royale#index'
  match 'battle_royale/:action', :controller => 'battle_royale'

  match 'blog(/:tag)' => 'articles#list', :as => :blogs
  
  scope 'articles', :controller => 'articles' do
    match 'view/:id', :action => 'view', :as => :article
    match ':id/atom', :action => 'article_atom'
  end

  match 'issues' => 'issue#index'

  scope 'issues', :controller => 'issue' do
    match 'show/:id', :action => 'show', :as => :issue
    match ':action/:id'
  end

  
  #######TEMP REMOVE
  # scope :module => 'formageddon', :as => 'formageddon' do    
  #   resources :formageddon_threads, :controller => 'threads', :path => '/formageddon/threads'
  #   resources :formageddon_contact_steps, :controller => 'contact_steps', :path => '/formageddon/contact_steps'
  # end
  # 
  # 
  # 
  # 
  # 
  # # Install the default route as the lowest priority.
  # map.connect ':controller/:action/:id'
  

  resources :contact_congress_letters, :only => [:index, :show, :new, :update] do
    get 'create_from_formageddon', :on => :collection # create uses POST and we'll be redirecting to create
    get 'get_recipients', :on => :collection 
    get 'delayed_send', :on => :collection
    get 'get_replies', :on => :collection
  end
  
  match 'howtouse' => 'about#howtouse'
  
  scope :controller => 'account' do
    for action in %w{ login why logout signup welcome contact_congress}
      match action, :action => action
    end
    
    match 'register', :action => 'signup'
    match 'account/confirm/:login', :action => 'confirm'
  end

  scope :controller => 'comments' do
    match 'comments/all_comments/:object/:id', :action => 'all_comments'
    match 'comments/atom/:object/:id', :action => 'atom_comments'
  end

  match 'users/:login/profile' => 'profile#show', :as => :user_profile

  scope 'users/:login' do

    scope 'profile' do 
      resource :political_notebook do
        collection do
          post :update_privacy
          get :feed
        end
        resources :notebook_links do
          collection do
            get :faceform
          end
        end
        resources :notebook_videos
        resources :notebook_notes
        resources :notebook_files    
      end
    
      scope 'friends', :controller => 'friends' do
        for action in %w{ import_contacts like_voters invite_contacts near_me invite invite_form }
          match action, :action => action, :as => 'friends_' + action
        end

        for action in %w{ confirm deny } do
          match action + '/:id', :action => action, :as => 'friends_add_' + action
        end
      end
  
      resources :friends

      scope :controller => 'profile' do
        for action in %w{ actions items_tracked watchdog edit_profile bills_supported tracked_rss user_actions_rss bills_opposed my_votes bills comments issues committees groups } do
          match action, :action => action, :as => 'user_' + action
        end

        match ':person_type', :action => 'person'
      end
    end # profile
    
    match 'feeds/:action(/:key)', :controller => 'user_feeds'
    
  end # users/:login

  match 'video/rss' => 'video#all', :format => 'atom'

  scope :controller => 'roll_call' do
    match 'roll_call/text/summary/:id', :action => 'summary_text'      
    match 'vote/:year/:chamber/:number(/:state)', :action => 'by_number', :year => /\d{4}/, :chamber => /[hs]/, :number => /\d+/, :state => /\w{2}/
  end

  match 'tools(/:action(/:id))', :controller => 'resources', :as => 'tools'

  match '/widgets' => 'widgets#index', :as => 'widgets'
  match '/widgets/deprecated' => 'widgets#deprecated', :as => 'deprecated_widgets'
  match '/widgets/bill' => 'widgets#bill', :as => 'bill_widget'
  match '/widgets/bills' => 'widgets#bills', :as => 'bills_widget'
  match '/widgets/people' => 'widgets#people', :as => 'people_widget'
  match '/widgets/group' => 'widgets#group', :as => 'group_widget'

  match 'api' => 'api#index'
  match 'api/bill/text_summary/:id' => 'bill#status_text'
  match 'api/roll_call/text_summary/:id' => 'roll_call#summary_text'
  match 'api(/:action(/:id)(.:format))', :controller => 'api'

  # Temporary routes for health care legislation
  match 'baucus_bill_health_care.html' => 'index#s1796_redirect'
  match 'presidents_health_care_proposal' => 'index#presidents_health_care_proposal'
  match 'senate_health_care_bill' => 'bill#text', :id => '111-h3590', :version => 'ocas'
  match 'house_reconciliation' => 'index#house_reconciliation'
  match 'pipa' => 'index#pipa'

  match ':controller(/:action(/:id))'
  #match '*path' => 'index#notfound' #unless Rails.application.config.consider_all_requests_local
  
end  

app/controllers/about_controller.rb
class AboutController < ApplicationController
  skip_before_filter :has_accepted_tos?
  skip_before_filter :store_location, :only => ["privacy_policy","terms_of_service"]

  def index
    @page_title = 'About Open Congress'
  end

  def blog
    @page_title = 'About OpenCongress Blog'
  end

  def resources
    @page_title = "General Overview / Information about Congress"
  end

  def congress
    @page_title = 'About Congress'
  end

  def howtouse
    @page_title = 'How To Use Open Congress'
  end

  def code
    @page_title = 'OpenCongress for Developers'
    require 'bluecloth'
    @readme = BlueCloth.new(Rails.root.join("README.md").read).to_html
  end
  
  def donate 
    render :layout => 'donate'
  end

  def donate_thanks
    render :layout => 'donate'
  end

  def beta_feedback
    @page_title = "Feedback"
  end

  def rss
  	@page_title = "Use RSS to Easily Track Developments in Congress"
  end

  def political_notebooks
     @page_title = "About My Political Notebook"
  end

  def screencast
    @page_title = "Screencast"
  end

  def terms_of_service
     @page_title = "Terms of Service and Comment Policy"
  end                                                   
  
  def privacy_policy
     @page_title = "Privacy Policy"
  end
  
  def version3
    @page_title = 'Announcing OpenCongress v3'
  end
  

end

app/helpers/about_helper.rb
module AboutHelper
  def learn_about(subject)
    require 'bluecloth'
    BlueCloth.new(render(:partial => "#{subject}/learn")).to_html
  end
end

app/views/about/beta_feedback.html.erb
<p>When we launched this beta version of OpenCongress in February 2007, we solicited feedback on the site from a wide audience of users and commentators. in fact, we've already responded to many of the comments below and have introduced new features to address our users' requests! To send us a suggestion, please visit our <a href="/gossip/suggestion">suggestion form</a> or <a href="/contact">contact us</a>. Please find below excerpts of their initial feedback, which we continue to collect and which we use centrally in developing new features for OpenCongress.</p>

	<p class="line"></p>
	
<p>Marc Laitin: this is really great (and quite nicely designed). I do have one quick thought/comment. I've been trying to track the progress of some bills for some other projects, in particular the minimum wage bill. I did a search for minimum wage and found the bill i wanted: http://www.opencongress.org/bill/110-h2/show -- And there is a ton of great information right there. But, it doesn't appear to have any place that summarizes or describes what the next step is for the bill. Right now it looks like the House and Senate have passed the bill with overwhelming majorities, which is correct, but what it doesn't say explicitly is that the Senate passed an amended version which is now sent back to the House where Pelosi can do one of, I think, three things. I don't even remotely know enough about House/Senate procedure to suggest a direction to proceed here to accurately list where a bill needs to go next to continue its march towards a presidential signature, but that might be something worth putting in the hopper (which i'm sure is full of other even better ideas).</p>

	<p class="line"></p>
	
<p>Chad Lupkes: Is the project willing to help launch similar sites for state legislatures I know that WashingtonVotes.org has been up for a while, and wa.billhop.com is trying to get enough interest to launch, but your interface is another great potential tools for us here in the Evergreen state. If something like this could be done, please keep me informed on the development.</p>

	<p class="line"></p>
	
<p>Cory Doctorow track things by email, like this <a href="http://theyworkforyou.com/alert/">this.</a></p>

	<p class="line"></p>
	
<p>Mike Beaumont: First of all, let me just say that Open Congress has incredible potential, and I'm really looking forward to using it.</p>

<p>I do advocacy work for the ONE Campaign and for CARE, so the ability to track legislation and interpret it in a meaningful way is essential to my work.</p>

<p>I do have one suggestion/question? Do you guys plan on implementing any sort of "My Open Congress" type sign-in feature? I'd love to be able to start an account, and then be able to track legislation, focus on key issues, and have customized RSS feeds as well. So I'd have like my own customized Open Congress page. Maybe you can even allow users to create their own customized sidebar widgets, so if I had a blog that focused on certain issues I could add a legislative tracker to my sidebar or something like that...</p>

<p>Anyway, great job so far, I've been sending the link around to all my colleagues. Thanks!</p>

	<p class="line"></p>
	
<p>First, kudos on your effort in opening up the inner workings of Congress making it much more accessible to the common public. I checked out OpenCongress.org but unfortunately I find it hard to use as your average citizen. Taking a quick glance at the front page, most of the stuff is over my head and looks dry and boring to me, so I have little incentive to dig in. As I see it, the crux of the problem lies around exposing the inner workings of Congress to the general public. The reality of the situation is that the general public has little to no interests of the inner workings of Congress. We are however interested in finding out how Congress is trying to address our issues but this does not translate into more exposure to the inner workings of Congress. So if someone like me with a MA in Information Technology and BS in CS that follows political news find the site hard to use, you can be assured that you have lost the better part of America that is less informed, less educated, and could care less about the dry inner workings of Congress.</p>

<p>Here's my suggestion if you wish to broaden your appeal. The home page should consist of the major political news as reported by major newspapers, etc. Based on the story, link it to the appropriate bills, etc that Congress are working on, not the other way around. It is way too dry and confusing to dive into the bills first without having an easy way to understand the context initially.</p>

<p>Good luck, Bob Ngu</p>
	<p class="line"></p>
	
<p>I don't have time to check this web site every day but there are issues affecting my (and everyone else's) lives.</p>

<p>How about an email posting once a day/hour/week?</p>

<p>gensha_2006</p>
	<p class="line"></p>
	
	<p>Your site is increadible, and I've been waiting for one like this for some time. Could you please add the ability to approve or disapprove a bill and keep a tally on both? Thank-you</p>

	<p>Trevor Redden</p>
	<p class="line"></p>
	
	<p>Thank you, This is an idea I've had for a while. I really hope it becomes popular. I have other ideas which may or may not have been considered.</p>

	<p>Functionality for people to log in, lets call them members. Members would have profiles indicating what interests them (e.g. environment, gun control, etc), what industry they work in, where they live, what their income is, .....</p>

	<p>Each bill would have tags indicating what the bill is about. Thus each member would be presented relavent bills based on thier profile.</p>

	<p>Functionality to allow senators to obtain feedback and statistics of feedback for those that live in the representatives state. Authentication of members may be required (e.g. social security number). I'm getting a little too excited so I'll stop now.</p>

	<p>Tim Pyne</p>
	<p class="line"></p>
	
	<p>Great website. I am going through your "How to Use OpenCongress" article, while I was going to add my representatives for my state (Texas) and there are a large number of representatives for my state (as well as a few others) and going through and adding all of them is time consuming. I would like to see OPML feed lists for representatives by state.</p>

	<p>Maybe even adding OPML lists for states that include both the representatives and senators so people only need to click one button to subscribe to all the congress/senate folk for their state.</p>

	<p>Great website. Look forward to using it throughly</p>

	<p>Michael Koby</p>

	<p class="line"></p>

	<p>I just found your site and I think its great! Haven't had too much time to surf around it yet, but there is one thing I would like to see done. More detailed information about each candidate. Especially about the platform they ran for office on and how their voting record coincides with it. This information could then be graphed and would be ag reat tool to get your website mass media attention. Hope to see it in action! Tim Moran</p>

	<p>Allow users to mark blog posts as "not related"</p>

	<p class="line"></p>

	<p>First off, great work people! Transparency in government goes a long way, and this tool is valuable to me as an active citizen.</p>

	<p>In the process of searching, I wanted a way to browse bills by date of introduction. I don't know if this [1] was the right page to use or not, though, because Last Action doesn't mean Date of Introduction</p>

	<p>Aaron Dulles-Coelho</p>

	<p class="line"></p>

	<p>I found Open Congress via a post at TPM. Upon my first few glances, I like it a lot. My suggestion: Congressional press release aggregation. It would be great to be able to go to ONE place and find what Members of Congress are sending out as press releases. I have not found anything with decent coverage. -- Marc Rumminger</p>

	<p class="line"></p>
	
	<p>It would be very nice indeed to have an RSS feed that shows ALL bills, so we could look at them as they go whizzing by, and have the option to add the RSS feed for that specific bill if we have any interest in it. If those RSS entries had links to the sponsoring legislators and any related committees, that would be terribly useful as well.</p>

	<p>Something like this is long overdue; I'm very, very glad someone has stepped up to the plate.</p>

	<p>Ken McGlothlen (Windsor CA)</p>
	<p class="line"></p>
	
	<p>I have just started checking opencongress.org regularly and appreciate what you have done with the site.</p>

	<p>I don't know if it's something you want to do with the site, but it would be really nice if there were a "one-stop shopping" source for senate and house hearings. In other words, links to daily hearings on one site so one does not have to go searching thru the committee or subcommittee sites just to see if something is happening on any particular day.</p>

	<p>I wish I could volunteer to do this, but do not have time to do so.</p>

	
		<p class="line"></p><p>Sincerely, john galloway</p>

	<p>Hello,</p>

	<p>First of all, I would just like to say congratulations on a wonderful website! OpenCongress.org is very easy to navigate, and the useful information is presented in a very easy-to-understand manner. I find myself using it quite frequently. Well done!</p>

	<p>But as with any undertaking, there are always room for improvements. Here are couple of features that I think opencongress.org could use:</p>

	<p>1) It would be useful to see particular committee/subcommittee on the pages that display information on individual Congressman and Senators. Because Congress is is so segmented, understanding what committee's members are on helps one to understand their particular positions on pending legislation.</p>

	<p>2) Related to my first comment, on the Committee/subcommittee pages, it would be useful to have a list of members on each particular committee or subcommittee.</p>

	<p>I hope you will take my suggestions under consideration. Either way, thank you for a wonderful information tool.</p>

	<p>Sincerely,</p>

	<p>Tom Jackman</p>

	<p class="line"></p>
	
	<p>Something that you may not have yet considered: integrating geotags into your service.</p>

	<p>The ability to view data from and about Open Congress in google earth along with annotations would be a great way to visualize and engage issues locally as well as nationally.</p>

	<p>I'll probably write a blog post thinking this through a bit more in the next few weeks. If I do, I'll shoot you a link.</p>

	<p>-Timothy Moenk</p>

		<p class="line"></p>
		
	<p>Would you add the Federal Register to your search engine? -John Walling</p>

	<p><a href="http://doc.weblogs.com/2007/04/12">http://doc.weblogs.com/2007/04/12</a></p>

	<p>The first question that came to mind was, How much money does Rep. Ric Keller get from the the entertainment industry for floating HR 1689 — the Curb Illegal Downloading on College Campuses Act of 2007?</p>

	        <p>I looked for the answer in OpenCongress.org's page on Keller, where there are four stories about Keller: one from Slashdot, one from the Orlando Sentinel, one from Download Splog, aka "Communication Software Review" (speaking of piracy, it was scraped from Chronicles of Dissent), and one from CannonFire. Here's Keller's own statement about the bill, which he says "would expand the allowable use of funds...to provide for innovative on-campus, anti-piracy pilot programs designed to reduce digital piracy." He concludes, "This troubling trend on college campuses has led to lawsuits against computer users who engage in illegal downloading of copyrighted content. These suits force colleges to spend a great deal of time and resources responding to notices of illegal downloading." Translation: Take our bribe and we'll call off the RIAA's goons. The bill claims it will "improve the security and integrity of campus computer networks" and "save telecommunications bandwidth costs, while ensuring such bandwidth is first and foremost made available for research and education-related purposes." Never mind the fact that file sharing itself is at the heart of the Web's design, and that universities and even governments now share files using BitTorrent — itself a perfect example of how creative techies and users are bound to route around censorship. Of course, the RIAA loves the legislation. So does the MPAA (in a .pdf). More here, here, here and here.</p>

	<p><a href="http://cairns.typepad.com/blog/2007/02/opencongress_da.html">http://cairns.typepad.com/blog/2007/02/opencongress_da.html</a></p>

	<p>Some specific possibilities include user profiles with personalized feeds, the ability to write and edit articles, and tagging information....</p>

app/views/about/code.html.erb
<div id="heading">
	<h2><%= @page_title %></h2>
</div>

<div class="padding">
<div class="pretty-text">

<div class="col1">
<p>At its core, OpenCongress is an open-source Ruby on Rails application for aggregating and managing open government data. Right now the opencongress.org website is focused on US Congress, but our vision is to bring tools for transparency and engagement to constituents of any governing body, from the UN to your local neighborhood association.</p>

<p>We rely on developers from the community to help us improve the code. Can you help?</p>

<h2>Using OpenCongress data in your app</h2>
<p>You can use OpenCongress data in your applications, provided you meet the licensing requirements (shown at right). <%= link_to "Our API", api_path %> and <%= link_to "RSS feeds", "/about/rss" %> provide all the data on OpenCongress, from official bill info to news and blog coverage to user-generated votes on bills and more.</p>

<div><%= @readme.html_safe %></div>

</div><div class="col2">
   <h2>Quick links</h2>
      <p>OpenCongress is written with <a href="http://rubyonrails.com">Ruby on Rails</a>, backed by a <a href="http://www.postgresql.org">PostgreSQL</a> database and <a href="http://lucene.apache.org/solr/">Solr</a> full-text indexing. Our <a href="/wiki">Wiki</a> runs on <a href="http://semantic-mediawiki.org">Semantic MediaWiki</a>.</p>
   <ul class="pointy">
      <li><%= link_to 'Data API docs', api_path %> &amp; <%= link_to 'RSS feeds', '/about/rss' %></li>
      <li><%= link_to 'GitHub repository', 'http://github.org/opencongress/opencongress' %></li>
      <li><%= link_to 'Lighthouse tracking', 'https://participatorypolitics.lighthouseapp.com/projects/35587-opencongress/overview' %></li>
      <li><%= link_to 'Development roadmap', 'https://participatorypolitics.lighthouseapp.com/projects/35587/roadmap' %></li>
      <li><%= link_to 'Developer e-mail list', 'http://lists.ppolitics.org/listinfo.cgi/develop-ppolitics.org' %></li>
      <li>IRC: chat.freenode.net channel #opencongress</li>
   </ul>
   <br />
      <h2>Contact Us</h2>
      <p>Want to work on OpenCongress, show off your use of our API, or just say hello? Send us an e-mail (<script type="text/javascript">m("develop","opencongress","org","1");</script>) with a short note of introduction. We don't bite.</p>
      <%= render :partial => 'licensing_terms' %>
   </div>

</div>
</div>

app/views/about/political_notebooks.html.erb
<% unless logged_in? == false %>
  <p><%= link_to "Back to My Political Notebook", political_notebook_path(current_user.login), { :class => 'arrow-left' } %></p>
<% end %>

<p>"My Political Notebook" allows you to grab news articles, blog posts, YouTube? videos, and more and save them to your personal page in a matter of seconds. You'll have gathered a unique portfolio of everything you're following in the world of politics. It's also a simple way to remind yourself of articles, statistics, and opinions that are important to you.</p>

<p>Here's how it works. Everyone with a free "My OpenCongress" account now has a new tab in his or her profile, called "My Political Notebook". To get started, <a href="/register">register</a> or <a href="/login">login</a> to your "MyOC" account. Then, in the upper-right hand corner of the screen, click the link for "My Political Notebook" to visit the page where your content will be saved.</p>
<%= image_tag('about_mypn.png', :alt => "drag bookmark", :style => "float:right;margin-left:8px;padding:2px;border:1px solid #ccc;") %>
<p>There are three ways to add content to "My Political Notebook" (or "MyPN" for short). First, in the upper-right hand corner of your notebook, there's a bookmarklet. Drag this into your web browser's toolbar. Then, anytime you're on a webpage with something you want to save, just click on the "+MyPN" link in your toolbar. The bookmarklet will automatically fill in the title of the content you select, as in social bookmarking services like del.ico.us and others, but you can edit it and add your own written description and tags. You can also select a political issue area from our customized pull down menu so that OpenCongress can help direct you to any hot bills in Congress that are related to the content you are saving.</p>

<%= image_tag('about_mypn2.png', :alt => "click bookmarklet", :style => "float:right;margin-left:8px;padding:2px;border:1px solid #ccc;") %> 
<p>For example, let's say you're reading a blog post about the economy that you think is important. Click to save it to your notebook, where you can add notes on why you think it's noteworthy, and tag it as you prefer. There's also an optional drop-down box for "Issues", where you can for example select "economy". That way, when you click save, the blog post will appear in your notebook alongside a link to view the hot bills affecting the economy in Congress. In this way, My Political Notebook works to connect large-scale issue areas you're reading about (e.g., the economy) to the important details of the bills that directly affect them in Congress (e.g., unemployment extensions, or financial system bailout bills). It's about making the news concrete in the substance of bills.</p>

<%= image_tag('about_mypn3.png', :alt => "add to mypn", :style => "float:right;margin-left:8px;padding:2px;border:1px solid #ccc;") %> 
<p>A second way to add info to your notebook is directly from OpenCongress pages themselves. Let's say you're reading about a bill on OpenCongress and you want to have the bill's page handy for future reference or to share a finding with friend. Click the "+" sign at the top of the page next to the bill's official number (see example), and you'll be able to add it either to your page of My OpenCongress Tracked Items, or to Your Political Notebook. You might choose the former option when you're following the latest actions &amp; official details of a bill, and the latter when you want to be able to add your own opinion or comment on the bill in your notebook. As with your Tracked Items, Your Political Notebook can be shared with your friends and online communities -- anyone can subscribe to your personal RSS feed of MyPN content you've added and read your accompanying notes.</p>

<p>A third way is to add content manually using the links at the top of your MyPN page. As seen there, there are four types of content that can be added to MyPN: links, videos, notes, and files. Links can be any page on the web -- newspaper articles, blog posts, groups formed from social networking sites, policy statements from a campaign... anything out there. Videos can be embedded in your notebook from sites like YouTube?, Blip.tv, and others ... political satire welcomed. Notes are simply notes-to-self, giving you a platform to jot down the thoughts you want to remember or to state your opinion on a topic for your friends to read. Files can be any accepted file format -- charts, polling reports, party platforms, even the text of legislation.</p>

<p>To get a sense of "My Political Notebook" in action, take a look at <a href="/users/donnyshaw/profile/political_notebook">Donny Shaw's page</a> and the mix of content he's saved there. Feel free to follow him as he posts new content by clicking on the orange RSS icon in his MyPN tab. By using an RSS reader such as Google Reader or My Yahoo, you'll get automatic updates every time he posts new content to his notebook (more info on <a href="/about/rss">how to use RSS</a>). Feel free to contact us with questions, suggestions, or feature requests: <script type="text/javascript">m("writeus","opencongress","org", "1")</script></p>

<% unless logged_in? == false %>
  <p><%= link_to "Back to My Political Notebook", political_notebook_path(current_user.login), { :class => 'arrow-left' } %></p>
<% end %>